import { useEffect, useMemo, useRef, useState } from "react";
import { CircleSlash, ListFilter, Search, ShieldCheck, X } from "lucide-react";

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { AllowedAction, MemberCapacitySummary, RoleActionExecutor, WorkGraph, WorkSummary } from "../../../model/roleViews";
import { WorkGraphInspector } from "./WorkGraphInspector";
import { WorkGraphCompactList, WorkGraphView } from "./WorkGraphView";

type OwnerFilter="all"|"unassigned"|string;
type AttentionFilter="all"|"blocked"|"review";
type ConditionFilter="all"|string;
type PriorityFilter="all"|string;
const PHASE_LABELS={active:{label: "Active"},closed:{label: "Closed"}} as const;

/** Orchestrates filtering, graph selection and the inspector; graph/readiness rules stay server-owned. */
export function TeamWorksBoard({works,graph,members,allowedActions,teamId,actionsCurrent,onAction,onCompleted,selectedWorkId,onSelectWork,onOpenMember,onOpenHost,ownerFilter,attentionFilter,queryFilter,onFiltersChange,onOpenHostTools}:{
  works:WorkSummary[];graph:WorkGraph;members:MemberCapacitySummary[];allowedActions:AllowedAction[];teamId:string;actionsCurrent:boolean;onAction:RoleActionExecutor;onCompleted:()=>void;selectedWorkId?:string;onSelectWork:(workId:string|undefined)=>void;onOpenMember:(memberRunId:string)=>void;onOpenHost?:(workId:string)=>void;ownerFilter?:OwnerFilter;attentionFilter?:AttentionFilter;queryFilter?:string;onFiltersChange?:(filters:{owner:OwnerFilter;attention:AttentionFilter;query:string})=>void;onOpenHostTools?:()=>void;
}){
  const [localOwner,setLocalOwner]=useState<OwnerFilter>("all");const [localAttention,setLocalAttention]=useState<AttentionFilter>("all");const [localQuery,setLocalQuery]=useState("");const [condition,setCondition]=useState<ConditionFilter>("all");const [priority,setPriority]=useState<PriorityFilter>("all");const [filtersOpen,setFiltersOpen]=useState(false);const [compactSheet,setCompactSheet]=useState(false);
  const owner=ownerFilter??localOwner;const attention=attentionFilter??localAttention;const query=queryFilter??localQuery;
  const selected=works.find((work)=>work.work_id===selectedWorkId);const membersById=useMemo(()=>new Map(members.map((member)=>[member.agent_member_ref.id,member])),[members]);const attentionIds=useMemo(()=>new Set(graph.attention_work_ids),[graph.attention_work_ids]);
  const closeRef=useRef<HTMLButtonElement>(null);const sheetRef=useRef<HTMLElement>(null);const filterTriggerRef=useRef<HTMLButtonElement>(null);const filterCloseRef=useRef<HTMLButtonElement>(null);const filterSheetRef=useRef<HTMLDivElement>(null);const focusReturnWorkId=useRef<string>();
  const ownerIdentity=(work:WorkSummary)=>work.assignee_ref?.agent_member_id??work.assignee_membership_id??work.owner_actor_ref?.id??null;
  const conditions=useMemo(()=>Array.from(new Set(works.map((work)=>work.condition?.trim()).filter((value):value is string=>Boolean(value)))),[works]);const priorities=useMemo(()=>Array.from(new Set(works.map((work)=>work.priority?.trim()).filter((value):value is string=>Boolean(value)))),[works]);
  const visible=works.filter((work)=>{const ownerMatch=owner==="all"||(owner==="unassigned"?!ownerIdentity(work):ownerIdentity(work)===owner||work.owner_actor_ref?.id===owner);const attentionMatch=attention==="all"||(attention==="blocked"?attentionIds.has(work.work_id):work.phase==="review");const conditionMatch=condition==="all"||work.condition===condition;const priorityMatch=priority==="all"||work.priority===priority;const searchable=[work.work_id,work.title,work.context_markdown,work.completion_criteria_markdown,work.owner_actor_ref?.id,...work.prerequisite_work_ids,...(work.successor_work_ids??[])].filter(Boolean).join(" ").toLowerCase();return ownerMatch&&attentionMatch&&conditionMatch&&priorityMatch&&(!query.trim()||searchable.includes(query.trim().toLowerCase()));});
  useEffect(()=>{const media=window.matchMedia("(max-width: 1023px)");const sync=()=>setCompactSheet(media.matches);sync();media.addEventListener("change",sync);return()=>media.removeEventListener("change",sync);},[]);
  useEffect(()=>{if(selected){focusReturnWorkId.current=selected.work_id;closeRef.current?.focus();return;}if(focusReturnWorkId.current){const id=CSS.escape(focusReturnWorkId.current);[...document.querySelectorAll<HTMLButtonElement>(`[data-work-graph-node="${id}"], [data-work-compact-node="${id}"]`)].find((node)=>node.offsetParent!==null)?.focus();focusReturnWorkId.current=undefined;}},[selected?.work_id]);
  useEffect(()=>{if(!selected)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();onSelectWork(undefined);return;}if(!compactSheet)return;if(event.key !== "Tab")return;const focusable=[...(sheetRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]), [href], input:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])')??[])];if(!focusable.length)return;const first=focusable[0];const last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close);},[selected,onSelectWork,compactSheet]);
  const closeFilters=()=>{setFiltersOpen(false);filterTriggerRef.current?.focus();};
  useEffect(()=>{if(!compactSheet||!filtersOpen)return;filterCloseRef.current?.focus();const handle=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();closeFilters();return;}if(event.key!=="Tab")return;const focusable=[...(filterSheetRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex="-1"])')??[])];if(!focusable.length)return;const first=focusable[0];const last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener("keydown",handle);return()=>document.removeEventListener("keydown",handle);},[compactSheet,filtersOpen]);
  const updateFilters=(next:Partial<{owner:OwnerFilter;attention:AttentionFilter;query:string}>)=>{const filters={owner:next.owner??owner,attention:next.attention??attention,query:next.query??query};if(onFiltersChange)onFiltersChange(filters);else{setLocalOwner(filters.owner);setLocalAttention(filters.attention);setLocalQuery(filters.query);}};
  const clearFilters=()=>{updateFilters({owner:"all",attention:"all",query:""});setCondition("all");setPriority("all");};const filtersApplied=owner!=="all"||attention!=="all"||condition!=="all"||priority!=="all"||Boolean(query);
  const dependencyAction=selected?allowedActions.find((action)=>action.kind==="change_work_dependencies"&&action.target_ref.kind==="work"&&action.target_ref.id===selected.work_id):undefined;
  return <section aria-labelledby="team-works-title" data-testid="role-view-team-works">
    <header className="flex flex-wrap items-end justify-between gap-2 pt-4"><div><h2 id="team-works-title" className="text-base font-semibold">Shared Work graph</h2><p className="text-xs text-muted-foreground">Flat Work responsibilities connected by hard execution dependencies.</p></div><Button ref={filterTriggerRef} size="sm" variant="secondary" className="min-h-11 lg:min-h-0" aria-expanded={filtersOpen} aria-controls="team-work-filters" onClick={()=>filtersOpen?closeFilters():setFiltersOpen(true)}><ListFilter className="size-3.5"/>Filters</Button></header>
    {filtersOpen&&compactSheet&&<button type="button" aria-label="Close Work filters" className="fixed inset-0 z-40 bg-foreground/15" onClick={closeFilters}/>}<div ref={filterSheetRef} id="team-work-filters" role={compactSheet?"dialog":undefined} aria-modal={compactSheet&&filtersOpen||undefined} className={cn("mt-3 grid gap-2 border-y border-border/80 bg-card/70 py-3 lg:grid-cols-[minmax(16rem,1fr)_10rem_9rem_9rem_12rem]",!filtersOpen&&"hidden",compactSheet&&filtersOpen&&"agent-team-sheet-enter fixed inset-x-0 bottom-0 z-50 max-h-[88dvh] overflow-y-auto rounded-t-xl border bg-background p-4 shadow-xl")} aria-label="Work filters"><div className="mb-1 flex items-center lg:hidden"><h3 className="text-sm font-semibold">Filter Works</h3><button ref={filterCloseRef} type="button" className="ml-auto grid size-11 place-items-center rounded-md" aria-label="Close Work filters" onClick={closeFilters}><X className="size-4"/></button></div><label className="relative min-w-0"><span className="sr-only">Search Works</span><Search className="pointer-events-none absolute left-3 top-3 size-4 text-muted-foreground"/><input value={query} onChange={(event)=>updateFilters({query:event.target.value})} placeholder="Search title, context, relation or ID" className="agent-team-control h-10 w-full pl-9 pr-3 text-sm outline-none focus:border-primary"/></label><label><span className="sr-only">Owner</span><select value={owner} onChange={(event)=>updateFilters({owner:event.target.value})} className="agent-team-control h-10 w-full px-3 text-xs"><option value="all">All owners</option><option value="unassigned">Unassigned</option>{members.map((member)=><option key={member.agent_member_ref.id} value={member.agent_member_ref.id}>{member.display_name}</option>)}</select></label><label><span className="sr-only">Condition</span><select value={condition} onChange={(event)=>setCondition(event.target.value)} className="agent-team-control h-10 w-full px-3 text-xs"><option value="all">All conditions</option>{conditions.map((value)=><option key={value} value={value}>{value.replace(/_/g," ")}</option>)}</select></label><label><span className="sr-only">Priority</span><select value={priority} onChange={(event)=>setPriority(event.target.value)} className="agent-team-control h-10 w-full px-3 text-xs"><option value="all">All priorities</option>{priorities.map((value)=><option key={value} value={value}>{value.replace(/_/g," ")}</option>)}</select></label><div className="agent-team-control flex min-w-0 gap-0.5 p-0.5" role="group" aria-label="Attention filter">{(["all","blocked","review"] as const).map((value)=><button key={value} type="button" data-active={attention===value} className="agent-team-filter-choice min-w-0 flex-1 px-2 text-xs font-medium" onClick={()=>updateFilters({attention:value})}>{value==="blocked"?"attention":value}</button>)}</div></div>
    {visible.length?<div className={cn("lg:items-start",selected&&"lg:grid lg:grid-cols-[minmax(0,1fr)_22rem] lg:gap-3")}><div className="min-w-0"><WorkGraphView graph={graph} visibleWorks={visible} membersById={membersById} selectedWorkId={selectedWorkId} onSelectWork={onSelectWork}/><WorkGraphCompactList works={visible} selectedWorkId={selectedWorkId} onSelectWork={onSelectWork}/></div>{selected&&<div className="fixed inset-0 z-50 bg-foreground/15 lg:sticky lg:top-3 lg:z-auto lg:mt-3 lg:max-h-[calc(100vh-2rem)] lg:bg-transparent" onMouseDown={(event)=>{if(compactSheet&&event.target===event.currentTarget)onSelectWork(undefined);}}><aside ref={sheetRef} role="dialog" aria-modal={compactSheet||undefined} aria-labelledby="selected-work-title" data-testid="role-view-work-sheet" className="agent-team-sheet-enter absolute inset-x-0 bottom-0 max-h-[88dvh] overflow-y-auto rounded-t-xl border border-border bg-background p-4 shadow-xl lg:static lg:max-h-[calc(100vh-2rem)] lg:w-full lg:rounded-xl lg:shadow-none lg:animate-none"><WorkGraphInspector work={selected} allWorks={works} dependencyAction={dependencyAction} teamId={teamId} actionsCurrent={actionsCurrent} onAction={onAction} onCompleted={onCompleted} onClose={()=>onSelectWork(undefined)} onNavigate={onSelectWork} onOpenMember={onOpenMember} onOpenHost={onOpenHost} closeRef={closeRef}/></aside></div>}</div>:<div className="mt-3 border-y border-dashed border-border px-5 py-12 text-center"><CircleSlash className="mx-auto size-6 text-muted-foreground"/><h3 className="mt-3 text-sm font-medium">{works.length?"No Work matches these filters":"This Team has no durable Work yet"}</h3><p className="mt-1 text-xs text-muted-foreground">{works.length?"Reset filters to restore the full dependency graph.":"Open Host tools to create the first Work."}</p>{filtersApplied?<Button className="mt-4" size="sm" variant="secondary" onClick={clearFilters}>Reset filters</Button>:onOpenHostTools?<Button className="mt-4" size="sm" onClick={onOpenHostTools}><ShieldCheck className="size-3.5"/>Open Host tools</Button>:null}</div>}
    <span className="sr-only">Canonical lifecycle phases include {PHASE_LABELS.active.label} and {PHASE_LABELS.closed.label}.</span>
  </section>;
}
