import { ArrowRight, GitBranch } from "lucide-react";

import { cn } from "@/lib/utils";
import type { WorkSummary } from "../../../model/roleViews";
import { workReadinessPresentation } from "./WorkGraphView";

const COLUMNS=[{phase:"open",label:"Open"},{phase:"active",label:"Active"},{phase:"review",label:"Review"},{phase:"closed",label:"Closed"}] as const;

/** Read-only phase projection. Cards select Work; drag never implies a lifecycle write. */
export function WorkKanbanView({works,selectedWorkId,onSelectWork}:{works:WorkSummary[];selectedWorkId?:string;onSelectWork:(workId:string)=>void}){
  return <section className="mt-3 min-w-0 max-w-full" aria-labelledby="work-kanban-title" data-testid="team-work-kanban"><header className="mb-2"><h3 id="work-kanban-title" className="company-editorial-title text-lg">Work Kanban</h3><p className="text-[11px] text-muted-foreground">Four canonical phases. Cards are intentionally non-draggable; lifecycle changes use authorized actions.</p></header><div className="grid w-full min-w-0 max-w-full snap-x snap-mandatory grid-flow-col auto-cols-[minmax(min(17rem,calc(100vw-7rem)),1fr)] gap-3 overflow-x-auto overscroll-x-contain pb-3 xl:grid-flow-row xl:grid-cols-4 xl:auto-cols-auto" data-testid="work-kanban-columns" tabIndex={0} aria-label="Work Kanban columns; scroll horizontally to reach every phase">{COLUMNS.map((column)=>{const items=works.filter((work)=>work.phase===column.phase);return <section key={column.phase} data-work-phase-column={column.phase} className="min-w-0 snap-start scroll-ml-1 rounded-xl border border-border bg-secondary/20 p-3"><header className="flex items-center border-b border-border pb-2"><h4 className="text-xs font-semibold uppercase tracking-[.1em]">{column.label}</h4><span className="ml-auto text-xs tabular-nums text-muted-foreground">{items.length}</span></header><div className="mt-3 grid gap-2">{items.map((work)=><KanbanCard key={work.work_id} work={work} selected={work.work_id===selectedWorkId} onSelect={onSelectWork}/>)}{items.length===0&&<p className="rounded-lg border border-dashed border-border px-3 py-8 text-center text-[11px] text-muted-foreground">No {column.label.toLowerCase()} Work</p>}</div></section>})}</div></section>;
}

function KanbanCard({work,selected,onSelect}:{work:WorkSummary;selected:boolean;onSelect:(workId:string)=>void}){const readiness=workReadinessPresentation(work);const Icon=readiness.icon;return <button type="button" draggable={false} data-work-kanban-card={work.work_id} aria-pressed={selected} onClick={()=>onSelect(work.work_id)} className={cn("agent-team-panel min-w-0 rounded-lg bg-card p-3 text-left hover:border-primary/25 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary",selected&&"agent-team-selected")}><div className="flex items-center gap-2"><span className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">{work.condition!=="normal"?work.condition:work.priority}</span><span className="ml-auto font-mono text-[9px] text-muted-foreground">v{work.work_revision}</span></div><strong className="mt-2 block line-clamp-2 text-[13px] leading-snug">{work.title||work.work_id}</strong><span className={cn("mt-2 flex items-center gap-1.5 text-[10px] font-medium",readiness.tone)}><Icon className="size-3"/>{readiness.label}</span><span className="mt-2 flex items-center gap-1 border-t border-border/70 pt-2 text-[9px] text-muted-foreground"><GitBranch className="size-3"/>{work.prerequisite_work_ids.length} in · {work.successor_work_ids?.length??0} out<ArrowRight className="ml-auto size-3"/></span></button>}
