import { ArrowUpRight, Bot, ChevronDown, ChevronRight, CircleAlert, FilePlus2, FolderKanban, Info, Search, Sparkles } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { ArtField, EditorialTitle, ObjectEmblem } from "../visuals";

import { RelationChips } from "./RelationChips";
import type { CompanyOsWorkspaceData, CompanyOsWorkspaceTreeItem } from "./types";

function TreeItem({ item, depth = 0 }: { item: CompanyOsWorkspaceTreeItem; depth?: number }) {
  const hasChildren = Boolean(item.children?.length);
  const body = <span className="flex min-w-0 flex-1 items-start gap-1.5"><FolderKanban className="mt-0.5 size-3.5 shrink-0 text-muted-foreground" aria-hidden /> <span className="min-w-0 whitespace-normal leading-4">{item.label}{item.meta && <span className="text-muted-foreground"> · {item.meta}</span>}</span></span>;
  const indent = depth === 0 ? "pl-2" : depth === 1 ? "pl-5" : depth === 2 ? "pl-8" : "pl-11";
  const className = cn("flex w-full items-center gap-1.5 rounded-md py-1.5 text-left text-xs text-foreground hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring", indent, item.selected && "bg-primary/10 text-primary");
  return <li>
    {item.href ? <a href={item.href} data-company-os-ref={item.ref} className={className}>{hasChildren ? <ChevronDown className="size-3 shrink-0" /> : <span className="w-3" />}{body}</a> : <div data-company-os-ref={item.ref} className={className}>{hasChildren ? <ChevronDown className="size-3 shrink-0" /> : <span className="w-3" />}{body}</div>}
    {hasChildren && <ul>{item.children?.map((child) => <TreeItem key={child.id} item={child} depth={depth + 1} />)}</ul>}
  </li>;
}

/** Docs home: a company knowledge workspace, not a filesystem browser. */
export function DocsWorkspace({
  workspace,
  onCreate,
}: {
  workspace: CompanyOsWorkspaceData;
  onCreate?: (kind: "page" | "database") => void;
}) {
  const maintainedBy = workspace.maintainers ?? [];
  return (
    <main data-company-os-page="docs-workspace" data-company-os-fixture={workspace.fixtureId} data-company-os-ready="true" className="company-workbench h-full overflow-auto bg-background">
      <ArtField />
      <div className="relative mx-auto grid min-h-full max-w-[1480px] lg:grid-cols-[240px_minmax(0,1fr)_280px]">
        <aside className="hidden border-b border-border bg-card/55 p-4 backdrop-blur-sm lg:block lg:border-b-0 lg:border-r" aria-label="Document tree"><div className={cn("mb-4 flex items-center justify-between rounded-xl border border-transparent px-2 py-2", workspace.rootSelected && "border-primary/20 bg-primary/[0.07] text-primary")}><div className="flex items-center gap-2"><ObjectEmblem kind="docs" className="size-8 rounded-lg" /><p className="text-sm font-semibold">Company</p></div><Button size="icon" variant="ghost" aria-label="Create a document"><FilePlus2 /></Button></div><ul className="space-y-0.5">{workspace.tree.map((item) => <TreeItem key={item.id} item={item} />)}</ul></aside>
        <section className="min-w-0 px-6 py-7 sm:px-9"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] text-muted-foreground">Company&nbsp;&nbsp; / &nbsp;&nbsp;Operating system</p><EditorialTitle className="mt-7">Company knowledge</EditorialTitle><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{workspace.description ?? "The source of truth for how the company works—connecting operating structure, durable records, decisions, and accountable actors."}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => onCreate?.("page")}><FilePlus2 />New page</Button><Button variant="outline" size="sm"><Sparkles />Ask an agent</Button></div></header>
          <section className="mt-7 flex max-w-xl items-start gap-3 border-b border-border pb-6"><Info className="mt-0.5 size-5 shrink-0 text-primary" /><div><h2 className="company-editorial-title text-xl">How this company works</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">We organize durable context into clear operating areas. Documents create governed work; results and evidence return here.</p></div></section>
          <div className="mt-6 grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
            <section className="border-r-0 border-border xl:border-r xl:pr-6"><h2 className="company-editorial-title text-2xl">Operating areas</h2><div className="mt-3 divide-y divide-border/70">{workspace.spaces.map((space) => <a key={space.id} href={space.href} className="group flex items-start gap-3 py-2.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ObjectEmblem kind={/brand|legal|trademark/i.test(space.name) ? "module" : "docs"} className="size-7 rounded-md" /><span className="min-w-0 flex-1"><span className="block text-sm font-medium group-hover:text-primary">{space.name}</span><span className="mt-0.5 block text-[11px] leading-4 text-muted-foreground">{space.summary ?? space.countLabel ?? "Connected company knowledge"}</span></span><ArrowUpRight className="mt-1 size-3 text-muted-foreground opacity-0 transition group-hover:opacity-100" /></a>)}</div></section>
            <section><h2 className="company-editorial-title text-2xl">Needs structure</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Governance proposals identify areas that need a durable home or accountable owner.</p>{workspace.proposal ? <a data-company-os-ref={workspace.proposal.id} href={workspace.proposal.href} className="mt-4 flex items-center gap-3 rounded-lg border border-primary/25 bg-primary/[0.035] p-3 hover:bg-primary/[0.07]"><ObjectEmblem kind="module" className="size-9 rounded-lg" /><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{workspace.proposal.label}</span><span className="text-xs text-muted-foreground">Structure proposal awaiting governed review</span></span><Badge tone="warn">Proposed</Badge></a> : <div className="mt-4 flex gap-2 rounded-lg border border-dashed border-border p-3 text-xs text-muted-foreground"><CircleAlert className="size-4" />No unresolved structure proposal.</div>}</section>
          </div>
          <section className="mt-6 border-t border-border pt-5"><div className="flex items-center justify-between"><h2 className="company-editorial-title text-xl">Recent company records</h2><div className="flex h-8 w-52 items-center gap-2 rounded-md border border-input bg-card px-2 text-[11px] text-muted-foreground"><Search className="size-3.5" />Search knowledge…</div></div><div className="mt-3 overflow-hidden rounded-lg border border-border bg-card/70"><div className="grid grid-cols-[minmax(0,1fr)_8rem_6rem] border-b border-border bg-muted/25 px-3 py-2 text-[9px] font-semibold uppercase tracking-wider text-muted-foreground"><span>Record</span><span>System</span><span>Status</span></div>{workspace.recentlyUpdated?.slice(0, 4).map((link) => <a key={link.id} href={link.href} data-company-os-ref={link.id} className="grid grid-cols-[minmax(0,1fr)_8rem_6rem] items-center border-b border-border/70 px-3 py-2.5 text-xs last:border-0 hover:bg-muted/30"><span className="truncate font-medium">{link.label}</span><span className="text-muted-foreground">Docs</span><span className="text-status-good">Linked</span></a>) ?? <p className="p-3 text-xs text-muted-foreground">No recent records.</p>}</div></section>
          <section className="mt-6"><h2 className="company-editorial-title text-xl">Maintained by agents</h2><p className="mt-1 text-xs text-muted-foreground">Standing Agents keep structure and operating context current through governed Actions.</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{maintainedBy.length ? maintainedBy.map((agent) => <a key={agent.id} href={agent.href} data-company-os-ref={agent.id} className="flex items-center gap-3 rounded-lg border border-border bg-card/65 p-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-primary/10 text-primary"><Bot className="size-5" /></span><span className="min-w-0"><span className="block truncate text-sm font-medium">{agent.label}</span><span className="block text-[11px] text-muted-foreground">Standing Agent · governed maintainer</span></span></a>) : <div className="rounded-lg border border-dashed border-border p-3 text-xs text-muted-foreground">No Standing Agent maintainer is present in this projection.</div>}</div></section>
        </section>
        <aside className="hidden border-t border-border bg-card/55 p-5 backdrop-blur-sm lg:block lg:border-l lg:border-t-0" aria-label="Structure context"><section className="rounded-xl border border-border bg-card/75 p-4"><div className="flex items-center gap-2"><ObjectEmblem kind="docs" className="size-8 rounded-lg" /><h2 className="company-editorial-title text-xl">Structure health</h2></div>{workspace.structureNotes?.length ? <dl className="mt-4 space-y-3">{workspace.structureNotes.map((note) => <div key={note.label} className="flex items-center justify-between gap-3 text-xs"><dt className="text-muted-foreground">{note.label}</dt><dd className={note.tone === "warning" ? "font-medium text-status-warn" : "font-medium text-foreground"}>{note.value}</dd></div>)}</dl> : <p className="mt-3 text-xs leading-5 text-muted-foreground">Structure signals appear when a governed audit supplies them.</p>}</section>
          <section className="mt-6 space-y-2"><h2 className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">Connected structure</h2><p className="text-xs leading-5 text-muted-foreground">These records are affected by the current space structure.</p><RelationChips links={workspace.structureLinks ?? workspace.suggestions} emptyLabel="No connected structure is supplied." /></section>
          <section className="mt-6 space-y-2"><h2 className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">Suggested connections</h2><RelationChips links={workspace.suggestions} emptyLabel="No suggestions supplied." /></section>
          {workspace.proposal && <section data-company-os-ref={workspace.proposal.id} className="mt-6 rounded-lg border border-primary/20 bg-primary/5 p-3"><Sparkles className="size-4 text-primary" aria-hidden /><h2 className="mt-2 text-sm font-semibold">Structure proposal</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">A proposal is visible for review; it does not change the structure by itself.</p><a href={workspace.proposal.href} className="mt-3 inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline">{workspace.proposal.label}<ChevronRight className="size-3" /></a></section>}
        </aside>
      </div>
    </main>
  );
}
