import { useEffect, useState } from "react";
import { Building2, Filter } from "lucide-react";
import { Button } from "@/components/ui/button";
import { fetchRoleView, type CompanyWorkIndexData, type RoleView } from "../model/roleViews";
import type { SelectionState } from "../app/selection";
import { AttentionStrip, ViewProvenance, ViewState, WorkTable } from "./RoleViewPrimitives";

export function CompanyWorkIndex({apiUrl,space,project,refreshKey,selection,onSelectionChange}:{apiUrl:string;space:string;project:string;refreshKey?:string;selection:SelectionState;onSelectionChange:(next:Partial<SelectionState>)=>void}){
  const [view,setView]=useState<RoleView<CompanyWorkIndexData>|null>(null);const [error,setError]=useState<string|null>(null);const [loading,setLoading]=useState(true);
  useEffect(()=>{let live=true;setLoading(true);setError(null);const params=new URLSearchParams();for(const [key,value] of [["team_id",selection.workTeamId],["mission_id",selection.workMissionId],["node_id",selection.workNodeId],["host_id",selection.workHostId],["member_id",selection.workMemberId],["phase",selection.workStatus],["priority",selection.workPriority]] as const)if(value)params.append(key,value);fetchRoleView<CompanyWorkIndexData>(apiUrl,`/v1/views/company-work?${params}`,{space,project}).then(v=>live&&setView(v)).catch(e=>live&&setError(String(e))).finally(()=>live&&setLoading(false));return()=>{live=false}},[apiUrl,space,project,refreshKey,selection.workTeamId,selection.workMissionId,selection.workNodeId,selection.workHostId,selection.workMemberId,selection.workStatus,selection.workPriority]);
  return <div className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><div className="mb-2 flex items-center gap-2 text-xs uppercase tracking-[.16em] text-primary"><Building2 className="size-4"/>Organization aggregate</div><h1 className="text-2xl font-semibold">Company Work</h1><p className="mt-1 text-sm text-muted-foreground">Every row remains owned by its flat Agent Team.</p></div>{view&&<ViewProvenance view={view}/>}</header><ViewState loading={loading} error={error}>{view&&<><AttentionStrip view={view}/><div className="flex items-center gap-2"><Filter className="size-4 text-muted-foreground"/><span className="text-xs text-muted-foreground">{view.data.page.item_count} Work items</span>{Object.values(selection).some(Boolean)&&<Button size="sm" variant="ghost" onClick={()=>onSelectionChange({workTeamId:undefined,workMissionId:undefined,workNodeId:undefined,workHostId:undefined,workMemberId:undefined,workStatus:undefined,workPriority:undefined})}>Clear filters</Button>}</div><WorkTable items={view.data.items} onOpen={work=>onSelectionChange({surface:"team",teamId:work.team_id,teamWorkId:work.work_id})}/></>}</ViewState></div>
}
