import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, GitMerge, Inbox, RadioTower, RefreshCw, ShieldCheck, Users } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Markdown } from "@/components/workbench/Markdown";
import { TeamCapacityStrip } from "@/components/workbench/team/TeamCapacityStrip";
import { TeamConversationStream } from "@/components/workbench/team/TeamConversation";
import { TeamMembersCapacity } from "@/components/workbench/team/TeamMembersCapacity";
import { TeamMessageComposer } from "@/components/workbench/team/TeamMessageComposer";
import { TeamWorksBoard } from "@/components/workbench/team/TeamWorksBoard";
import { fetchRoleView, type HostConsoleData, type MessageSummary, type RoleActionExecutor, type RoleView } from "../model/roleViews";
import { AttentionStrip, ViewProvenance, ViewState } from "./RoleViewPrimitives";
import { RoleActionPanel } from "./RoleActionPanel";

export function HostConsole({apiUrl,space,project,teamId,teamRunId,selectedWorkId,selectedMemberRunId,refreshKey,onAction,actionsCurrent,onSelectionChange}:{apiUrl:string;space:string;project:string;teamId:string;teamRunId?:string;selectedWorkId?:string;selectedMemberRunId?:string;refreshKey?:string;onAction:RoleActionExecutor;actionsCurrent:boolean;onSelectionChange:(next:Record<string,unknown>)=>void}) {
  const [view,setView] = useState<RoleView<HostConsoleData>|null>(null);
  const [error,setError] = useState<string|null>(null);
  const [loading,setLoading] = useState(true);
  const [refresh,setRefresh] = useState(0);
  const [replyTo,setReplyTo] = useState<MessageSummary|null>(null);
  useEffect(() => { let live=true; setLoading(true); fetchRoleView<HostConsoleData>(apiUrl,`/v1/views/host-console/${encodeURIComponent(teamId)}`,{space,project}).then((value) => { if(live){setView(value);setError(null);} }).catch((reason) => {if(live)setError(String(reason));}).finally(() => {if(live)setLoading(false);}); return () => {live=false;}; },[apiUrl,space,project,teamId,refreshKey,refresh]);
  if (!view) return <div className="h-full flex-1 overflow-y-auto"><ViewState loading={loading} error={error}>{null}</ViewState></div>;
  const allWorks = uniqueWorks(view.data.work_queues);
  const selectedWork = allWorks.find((work) => work.work_id === selectedWorkId);
  const selectedMember = view.data.member_runtime.find((member) => member.current_member_run_ref === selectedMemberRunId);
  const contextualActions = view.allowed_actions.filter((action) => (selectedWork && action.target_ref.kind === "work" && action.target_ref.id === selectedWork.work_id) || (selectedMemberRunId && action.target_ref.kind === "member_run" && action.target_ref.id === selectedMemberRunId));
  const contextualKeys = new Set(contextualActions.map((action) => `${action.kind}:${action.target_ref.kind}:${action.target_ref.id}`));
  const fallbackActions = view.allowed_actions.filter((action) => !contextualKeys.has(`${action.kind}:${action.target_ref.kind}:${action.target_ref.id}`) && !["send_message","reply_message","request_decision"].includes(action.kind));
  const canMutate = actionsCurrent && view.freshness === "current" && !loading && !error;
  const completed = () => setRefresh((value) => value+1);
  return <main className="h-full flex-1 overflow-y-auto p-3 sm:p-5" data-testid="authenticated-host-console"><div className="mx-auto max-w-[1500px] space-y-4">
    <header className="rounded-xl border border-border bg-card px-4 py-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.15em] text-primary"><ShieldCheck className="size-3.5"/>Host responsibility</div><h1 className="mt-1 text-xl font-semibold sm:text-2xl">Host Console</h1><p className="mt-1 text-xs text-muted-foreground">{view.data.mission_context?.title ?? view.data.mission_ref} · Team {view.data.team_ref}</p></div><div className="flex flex-wrap items-center justify-end gap-2"><Button size="sm" variant="secondary" onClick={() => onSelectionChange({teamMode:"workspace"})}>Team Workspace</Button><ViewProvenance view={view}/></div></div>
      <div className="mt-3 grid gap-2 border-t border-border pt-3 sm:grid-cols-4"><HeaderFact label="Supervisor" value={view.data.team_supervisor ? `${view.data.team_supervisor.status} · g${view.data.team_supervisor.generation}` : "not observed"}/><HeaderFact label="Supervisor current" value={view.data.team_supervisor ? String(view.data.team_supervisor.current) : "unknown"}/><HeaderFact label="NodeDaemon parent" value={`${view.data.daemon_summary.node_id} · ${view.data.daemon_summary.lease_status ?? "unknown"}`}/><HeaderFact label="Recovery" value={`${view.data.runtime_recovery.length} command${view.data.runtime_recovery.length === 1 ? "" : "s"}`}/></div>
    </header>
    {error && <div role="alert" className="flex flex-wrap items-center gap-2 rounded-lg border border-status-warn/35 bg-status-warn/10 p-3 text-xs"><span className="min-w-0 flex-1">HostConsole refresh failed. Last-good truth remains visible; every action is disabled. {error}</span><Button size="sm" variant="secondary" onClick={completed}>Retry</Button></div>}
    {loading && <div role="status" className="flex items-center gap-2 text-xs text-muted-foreground"><RefreshCw className="size-3.5 animate-spin"/>Refreshing Host-only authority…</div>}
    <AttentionStrip view={view}/>
    {view.data.mission_context && <section className="rounded-xl border border-border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-sm font-semibold">Mission context</h2><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{view.data.mission_context.status} · {view.data.mission_context.id}</p></div>{view.data.mission_context.log.length > 0 && <span className="text-[10px] text-muted-foreground">{view.data.mission_context.log.length} latest log entries</span>}</div><div className="mt-3 grid gap-3 lg:grid-cols-2"><div><h3 className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Objective</h3><div className="mt-1 text-xs"><Markdown source={view.data.mission_context.objective} compact/></div></div><div><h3 className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Desired outcome</h3><div className="mt-1 text-xs"><Markdown source={view.data.mission_context.desired_outcome ?? "Not specified."} compact/></div></div></div></section>}
    <TeamCapacityStrip summary={view.data.pressure_summary}/>
    <div className="grid min-w-0 gap-4 xl:grid-cols-[minmax(0,1fr)_21rem]">
      <div className="min-w-0 space-y-4"><TeamWorksBoard works={allWorks} members={view.data.member_capacity} selectedWorkId={selectedWorkId} onSelectWork={(teamWorkId) => onSelectionChange({teamMode:"host",teamWorkId})} onOpenMember={(memberRunId) => onSelectionChange({teamMode:"host",memberRunId})}/><details className="rounded-xl border border-border bg-card" open={view.data.host_inbox.length > 0}><summary className="flex min-h-12 cursor-pointer list-none items-center gap-2 px-4 text-sm font-semibold"><Inbox className="size-4 text-primary"/>Lead Inbox<span className="ml-auto rounded-full bg-primary/10 px-2 py-0.5 text-[10px] text-primary">{view.data.host_inbox.length}</span></summary><div className="border-t border-border p-3"><TeamConversationStream activity={[]} messages={view.data.host_inbox} truncated={false} onOpenWork={(teamWorkId) => onSelectionChange({teamMode:"host",teamWorkId})} onReply={setReplyTo}/></div></details><TeamMessageComposer actions={view.allowed_actions} members={view.data.member_capacity} works={allWorks} replyTo={replyTo} teamId={teamId} teamRunId={teamRunId} actionsCurrent={canMutate} onAction={onAction} onClearReply={() => setReplyTo(null)} onCompleted={completed}/></div>
      <aside className="min-w-0 space-y-4"><section className="rounded-xl border border-border bg-card p-4"><h2 className="text-sm font-semibold">Host attention</h2><div className="mt-3 grid grid-cols-2 gap-2"><Pressure label="Review" value={view.data.work_queues.review?.length ?? 0}/><Pressure label="Blocked" value={view.data.work_queues.blocked?.length ?? 0}/><Pressure label="Delivery recovery" value={view.data.deliveries_requiring_reconcile.length}/><Pressure label="Gate attention" value={view.data.gate_attention.length}/></div>{view.data.provider_capacity_attention.map((item,index) => <p key={index} className="mt-2 flex gap-2 text-[10px] text-muted-foreground"><AlertTriangle className="size-3 shrink-0"/>{item.reason}</p>)}</section>
        <section className="rounded-xl border border-border bg-card p-4"><h2 className="flex items-center gap-2 text-sm font-semibold"><Users className="size-4"/>Selected member context</h2>{selectedMember ? <div className="mt-3 space-y-2 text-xs"><p className="font-medium">{selectedMember.display_name}</p><p className="text-muted-foreground">{selectedMember.provider ?? "provider unknown"} · {selectedMember.model ?? "model unknown"}</p><p>{selectedMember.coordination_status ?? "no coordination status"} · runtime {selectedMember.runtime_state ?? "unknown"}</p><p>Native session {selectedMember.native_session_health ?? "unknown"}</p></div> : <p className="mt-3 text-xs text-muted-foreground">Select a current member below to scope runtime controls.</p>}<div className="mt-3 max-h-52 space-y-1 overflow-y-auto">{view.data.member_runtime.map((member) => <button key={member.agent_member_ref.id} disabled={!member.current_member_run_ref} onClick={() => member.current_member_run_ref && onSelectionChange({teamMode:"host",memberRunId:member.current_member_run_ref})} className="flex min-h-10 w-full min-w-0 items-center justify-between rounded-md px-2 text-left text-xs hover:bg-muted disabled:text-muted-foreground"><span className="truncate">{member.display_name}</span><span className="ml-2 shrink-0">{member.runtime_state ?? "unknown"}</span></button>)}</div></section>
        {contextualActions.length > 0 && <RoleActionPanel actions={contextualActions} onAction={onAction} actionsCurrent={canMutate} context={{teamId,teamRunId}} onCompleted={completed}/>}
        <details className="rounded-xl border border-border bg-card"><summary className="flex min-h-12 cursor-pointer list-none items-center gap-2 px-4 text-sm font-semibold"><GitMerge className="size-4 text-primary"/>More authorized actions<span className="ml-auto text-[10px] text-muted-foreground">{fallbackActions.length}</span></summary><div className="border-t border-border p-3"><RoleActionPanel actions={fallbackActions} onAction={onAction} actionsCurrent={canMutate} context={{teamId,teamRunId}} onCompleted={completed}/></div></details>
        {(view.data.team_supervisor || view.data.runtime_recovery.length > 0) && <section className="rounded-xl border border-border bg-card p-4"><h2 className="flex items-center gap-2 text-sm font-semibold"><RadioTower className="size-4"/>Runtime fabric</h2><p className="mt-2 text-xs text-muted-foreground">Supervisor and NodeDaemon health are reported independently. Recovery rows require explicit evidence; they are never replayed from the browser.</p>{view.data.team_supervisor && <p className="mt-3 break-all text-[10px]">{view.data.team_supervisor.owner_locator}</p>}</section>}
      </aside>
    </div>
    <section className="xl:hidden"><TeamMembersCapacity members={view.data.member_runtime} selectedMemberRunId={selectedMemberRunId} onOpenMember={(memberRunId) => onSelectionChange({teamMode:"host",memberRunId})}/></section>
  </div></main>;
}

function uniqueWorks(queues:HostConsoleData["work_queues"]) { const map = new Map<string,HostConsoleData["work_queues"][string][number]>(); Object.values(queues).flat().forEach((work) => map.set(work.work_id,work)); return [...map.values()].sort((left,right) => right.updated_at.localeCompare(left.updated_at)); }
function HeaderFact({label,value}:{label:string;value:string}) { return <div className="min-w-0 text-[10px]"><dt className="uppercase tracking-wider text-muted-foreground">{label}</dt><dd className="mt-1 truncate font-medium" title={value}>{value}</dd></div>; }
function Pressure({label,value}:{label:string;value:number}) { return <div className="rounded-md bg-muted/30 p-2"><dt className="text-[9px] uppercase tracking-wider text-muted-foreground">{label}</dt><dd className="mt-1 text-lg font-semibold tabular-nums">{value}</dd></div>; }
