import { useEffect, useState, type ReactNode } from "react";
import { Activity, AlertTriangle, BriefcaseBusiness, ChevronRight, Inbox, RadioTower, RefreshCw, Server, ShieldCheck, Users } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Avatar } from "@/components/workbench/Avatar";
import { Markdown } from "@/components/workbench/Markdown";
import { TeamConversationStream } from "@/components/workbench/team/TeamConversation";
import { TeamMembersCapacity } from "@/components/workbench/team/TeamMembersCapacity";
import { TeamMessageComposer } from "@/components/workbench/team/TeamMessageComposer";
import { fetchRoleView, type AllowedAction, type HostConsoleData, type MessageSummary, type RoleActionExecutor, type RoleView } from "../model/roleViews";
import { AttentionStrip, ViewProvenance, ViewState } from "./RoleViewPrimitives";
import { RoleActionPanel } from "./RoleActionPanel";

export function HostConsole({apiUrl,space,project,company,teamId,teamRunId,selectedWorkId,selectedMemberRunId,refreshKey,onAction,actionsCurrent,onSelectionChange,embedded=false}:{apiUrl:string;space:string;project:string;company?:string;teamId:string;teamRunId?:string;selectedWorkId?:string;selectedMemberRunId?:string;refreshKey?:string;onAction:RoleActionExecutor;actionsCurrent:boolean;onSelectionChange:(next:Record<string,unknown>)=>void;embedded?:boolean}) {
  const [view,setView] = useState<RoleView<HostConsoleData>|null>(null);
  const [error,setError] = useState<string|null>(null);
  const [loading,setLoading] = useState(true);
  const [refresh,setRefresh] = useState(0);
  const [replyTo,setReplyTo] = useState<MessageSummary|null>(null);
  useEffect(() => { let live=true; setLoading(true); fetchRoleView<HostConsoleData>(apiUrl,`/v1/views/host-console/${encodeURIComponent(teamId)}`,{space,project,company}).then((value) => { if(live){setView(value);setError(null);} }).catch((reason) => {if(live)setError(String(reason));}).finally(() => {if(live)setLoading(false);}); return () => {live=false;}; },[apiUrl,space,project,company,teamId,refreshKey,refresh]);
  const retry = () => setRefresh((value) => value+1);
  if (!view) return <div className="min-h-64"><ViewState loading={loading} error={error} identityLabel={`Host tools · ${teamId}`} onRetry={retry}>{null}</ViewState></div>;

  const allWorks = view.data.all_works;
  const resolvedTeamRunId = teamRunId ?? view.data.team_supervisor?.team_run_id;
  const runScopeMismatch = Boolean(resolvedTeamRunId && view.allowed_actions.some((action) => action.target_ref.kind === "team_run" && action.target_ref.id !== resolvedTeamRunId));
  const selectedWork = allWorks.find((work) => work.work_id === selectedWorkId)
    ?? allWorks.find((work) => view.data.host_inbox.some((message) => message.work_id === work.work_id))
    ?? allWorks.find((work) => work.condition === "blocked")
    ?? allWorks.find((work) => work.phase === "review");
  const selectedMember = view.data.member_runtime.find((member) => member.current_member_run_ref === selectedMemberRunId);
  const messageKinds=new Set(["send_message","reply_message","request_decision"]);
  const workActions=view.allowed_actions.filter((action) => action.target_ref.kind === "work" && (!selectedWork || action.target_ref.id === selectedWork.work_id));
  const teamRunActions=view.allowed_actions.filter((action) => action.target_ref.kind === "team_run" && action.kind !== "create_work" && !messageKinds.has(action.kind));
  const memberRunActions=view.allowed_actions.filter((action) => action.target_ref.kind === "member_run" && (!selectedMemberRunId || action.target_ref.id === selectedMemberRunId));
  const groupedKeys=new Set([...workActions,...teamRunActions,...memberRunActions].map((action) => `${action.kind}:${action.target_ref.kind}:${action.target_ref.id}`));
  const otherActions=view.allowed_actions.filter((action) => !messageKinds.has(action.kind) && !groupedKeys.has(`${action.kind}:${action.target_ref.kind}:${action.target_ref.id}`));
  const canMutate = actionsCurrent && view.freshness === "current" && !loading && !error && !runScopeMismatch;
  const supervisor=view.data.team_supervisor;

  const content = <section id="host-tools" className="space-y-3" data-testid="authenticated-host-console" aria-labelledby="host-tools-title">
    <header className="border-b border-border px-1 pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="sr-only">Host Console</h1><p className="agent-team-eyebrow flex items-center gap-2"><ShieldCheck className="size-3.5"/>Host Console</p><h2 id="host-tools-title" className="mt-1 text-xl font-semibold tracking-[-0.02em] sm:text-[26px]">Lead Inbox, runtime and decisions</h2><p className="mt-1 text-xs text-muted-foreground">Authenticated Host · {view.data.mission_context?.title ?? view.data.mission_ref}</p></div><div className="flex flex-wrap items-center justify-end gap-2">{embedded && <Button size="sm" variant="secondary" onClick={() => onSelectionChange({teamMode:"workspace"})}>Hide Host tools</Button>}<ViewProvenance view={view}/></div></div></header>
    <div className="flex items-center gap-2 rounded-lg border border-primary/25 bg-primary/[0.045] px-3 py-2 text-[11px]"><ShieldCheck className="size-4 shrink-0 text-primary"/><b className="text-primary">Protected-action boundary</b><span className="text-muted-foreground">Controls flow through exact server authority, Supervisor and RuntimeCommand. The browser never invents authority or fake success.</span></div>
    {error && <div role="alert" className="flex flex-wrap items-center gap-2 rounded-lg border border-status-warn/35 bg-status-warn/10 p-3 text-xs"><span className="min-w-0 flex-1">Host tools refresh failed. Last-good truth remains visible; every action is disabled. {error}</span><Button size="sm" variant="secondary" onClick={retry}>Retry</Button></div>}
    {runScopeMismatch && <div role="alert" className="rounded-lg border border-destructive/35 bg-destructive/5 p-3 text-xs">Host actions do not match the selected TeamRun. Controls are disabled until this exact run is projected.</div>}
    {loading && <div role="status" className="flex items-center gap-2 text-xs text-muted-foreground"><RefreshCw className="size-3.5 animate-spin"/>Refreshing Host-only authority…</div>}
    <AttentionStrip view={view}/>
    <div className="grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]">
      <div className="min-w-0 space-y-3">
        <section className="overflow-hidden border-y border-border" aria-labelledby="lead-inbox-title"><header className="flex min-h-12 items-center gap-2 border-b border-border px-1"><Inbox className="size-4 text-primary"/><h3 id="lead-inbox-title" className="company-editorial-title text-lg">Lead Inbox</h3><span className="text-[10px] text-muted-foreground">Host-only decision pressure</span><Badge className="ml-auto" tone={view.data.host_inbox.length ? "bad" : "muted"}>{view.data.host_inbox.length}</Badge></header><div className="border-b border-border py-3 xl:hidden"><CurrentDecision work={selectedWork} compact/></div>{view.data.host_inbox.length ? <TeamConversationStream activity={[]} messages={view.data.host_inbox} members={view.data.member_runtime} truncated={false} onOpenWork={(teamWorkId) => onSelectionChange({teamMode:"host",teamWorkId,teamTab:"works"})} onReply={setReplyTo}/> : <div className="px-4 py-8 text-center"><ShieldCheck className="mx-auto size-6 text-status-good"/><p className="mt-2 text-sm font-medium">No Host inbox pressure</p><p className="mt-1 text-xs text-muted-foreground">No projected member message currently requires Host attention.</p></div>}</section>

        <section className="border-y border-border px-1 py-4" aria-labelledby="run-controls-title"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="agent-team-eyebrow">Current TeamRun controls</p><h3 id="run-controls-title" className="company-editorial-title mt-1 text-lg">{resolvedTeamRunId ?? "No active TeamRun"}</h3></div><Badge tone={supervisor?.current ? "good" : "warn"}>{supervisor?.current ? "Supervisor current" : "authority attention"}</Badge></div><dl className="mt-4 grid grid-cols-2 border-y border-border sm:grid-cols-4 lg:grid-cols-8"><Pressure label="Members" value={view.data.pressure_summary.total_members}/><Pressure label="Ready" value={view.data.pressure_summary.ready_members} tone="good"/><Pressure label="Active turns" value={view.data.pressure_summary.active_turns} tone="running"/><Pressure label="Ready Work" value={view.data.pressure_summary.ready_work}/><Pressure label="Review" value={view.data.pressure_summary.review_work} tone="warn"/><Pressure label="Blocked" value={view.data.pressure_summary.blocked_work} tone="bad"/><Pressure label="Delivery recovery" value={view.data.deliveries_requiring_reconcile.length} tone="warn"/><Pressure label="Gate attention" value={view.data.gate_attention.length} tone="warn"/></dl>{teamRunActions.length > 0 && <div className="mt-4"><p className="mb-2 text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">TeamRun target · {resolvedTeamRunId}</p><RoleActionPanel compact actions={teamRunActions} onAction={onAction} actionsCurrent={canMutate} context={{teamId:view.data.team_ref,teamRunId:resolvedTeamRunId}} onCompleted={retry}/></div>}</section>

        {workActions.length > 0 && <section className="border-b border-border px-1 py-4" aria-labelledby="work-authority-title"><div className="flex items-center gap-2"><BriefcaseBusiness className="size-4 text-primary"/><h3 id="work-authority-title" className="text-sm font-semibold">Work authority</h3><Badge className="ml-auto">{groupActionsByTarget(workActions).length} targets</Badge></div><p className="mt-1 text-[11px] text-muted-foreground">Each action remains bound to the exact Work id and revision shown below.</p><ActionTargetGroups className="mt-3" actions={workActions} onAction={onAction} actionsCurrent={canMutate} context={{teamId:view.data.team_ref,teamRunId:resolvedTeamRunId}} onCompleted={retry}/></section>}

        <section className="border-y border-border px-1 py-4" aria-labelledby="supervisor-title"><div className="flex items-center gap-2"><RadioTower className="size-4 text-primary"/><h3 id="supervisor-title" className="text-sm font-semibold">Supervisor</h3></div>{supervisor ? <dl className="mt-3 grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><HeaderFact label="Generation" value={`generation ${supervisor.generation}`}/><HeaderFact label="Status" value={supervisor.status}/><HeaderFact label="Authority" value={supervisor.current ? "current" : "expired"}/><HeaderFact label="Node generation" value={`${supervisor.node_daemon_generation}`}/><HeaderFact label="Owner locator" value={supervisor.owner_locator}/><HeaderFact label="Heartbeat" value={new Date(supervisor.heartbeat_unix_ms).toLocaleTimeString()}/></dl> : <div className="mt-3 border-t border-dashed border-border py-4 text-xs text-muted-foreground">No Team Supervisor is projected. Runtime controls remain unavailable; the UI does not fall back to direct MemberRun dispatch.</div>}</section>

        <section className="border-y border-border" aria-labelledby="member-runtimes-title"><header className="flex min-h-12 items-center gap-2 px-1"><Users className="size-4 text-primary"/><h3 id="member-runtimes-title" className="text-sm font-semibold">Member runtimes</h3><Badge className="ml-auto">{view.data.member_runtime.length}</Badge></header><TeamMembersCapacity members={view.data.member_runtime} selectedMemberRunId={selectedMemberRunId} onOpenMember={(memberRunId) => onSelectionChange({teamMode:"workspace",teamConversation:view.data.member_runtime.find((member) => member.current_member_run_ref === memberRunId)?.agent_member_ref.id,memberRunId,teamTab:"members"})}/>{memberRunActions.length > 0 && <details className="border-t border-border"><summary className="flex min-h-10 cursor-pointer list-none items-center gap-2 px-1 text-xs font-semibold">MemberRun controls<Badge className="ml-auto">{groupActionsByTarget(memberRunActions).length} targets</Badge></summary><div className="border-t border-border py-3"><ActionTargetGroups actions={memberRunActions} onAction={onAction} actionsCurrent={canMutate} context={{teamId:view.data.team_ref,teamRunId:resolvedTeamRunId}} onCompleted={retry}/></div></details>}</section>

        <section className="border-t border-border py-4"><div className="mb-2 flex items-center gap-2 px-1"><Inbox className="size-4 text-primary"/><h3 className="text-sm font-semibold">Compose Team message</h3><span className="ml-auto text-[10px] text-muted-foreground">ordinary Message · not Steer</span></div><TeamMessageComposer actions={view.allowed_actions} members={view.data.member_capacity} works={allWorks} replyTo={replyTo} teamId={view.data.team_ref} teamRunId={resolvedTeamRunId} actionsCurrent={canMutate} onAction={onAction} onClearReply={() => setReplyTo(null)} onCompleted={retry}/></section>
      </div>

      <aside className="min-w-0 space-y-4">
        <div className="hidden xl:block"><CurrentDecision work={selectedWork}/></div>
        {view.data.runtime_recovery.length > 0 && <SideCard icon={AlertTriangle} title="Runtime recovery" tone="warn"><p className="text-xs text-muted-foreground">{view.data.runtime_recovery.length} RuntimeCommand records require evidence-backed resolution. Blind replay is prohibited.</p></SideCard>}
        <SideCard icon={RadioTower} title="Cross-machine collaboration" tone={(view.data.collaboration.attention_count ?? 0) ? "warn" : undefined}><p className="text-xs text-muted-foreground">{view.data.collaboration.state === "observed" ? `${view.data.collaboration.delegations?.length ?? 0} Delegations · ${view.data.collaboration.publication_count ?? 0} publications · ${view.data.collaboration.attention_count ?? 0} need attention` : view.data.collaboration.reason ?? "Company projection unavailable"}</p></SideCard>
        {selectedMember && <SideCard icon={Users} title="Selected member"><div className="flex items-center gap-3"><Avatar name={selectedMember.display_name} identity={`${selectedMember.agent_member_ref.id} ${selectedMember.role}`} size="lg" tone={selectedMember.runtime_state === "running" ? "running" : selectedMember.capacity === "available" ? "good" : "idle"}/><div className="min-w-0"><p className="truncate text-sm font-semibold">{selectedMember.display_name}</p><p className="truncate text-[10px] text-muted-foreground">{selectedMember.role}</p></div></div></SideCard>}
        <section className="space-y-3 border-y border-border py-4"><h3 className="text-xs font-semibold">Runtime and placement facts</h3><dl className="grid grid-cols-2 gap-3"><HeaderFact label="TeamRun" value={resolvedTeamRunId ?? "not projected"}/><HeaderFact label="Mission" value={view.data.mission_ref}/><HeaderFact label="Node" value={view.data.daemon_summary.node_id}/><HeaderFact label="Lease" value={view.data.daemon_summary.lease_status ?? "unknown"}/><HeaderFact label="Generation" value={view.data.daemon_summary.generation != null ? String(view.data.daemon_summary.generation) : "not projected"}/><HeaderFact label="Supervisor" value={supervisor ? `${supervisor.status} · g${supervisor.generation}` : "not observed"}/></dl></section>
        {view.data.mission_context && <details className="border-y border-border"><summary className="flex min-h-11 cursor-pointer list-none items-center gap-2 text-sm font-semibold">Mission context<ChevronRight className="ml-auto size-3.5"/></summary><div className="space-y-3 border-t border-border py-4"><div><p className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">Objective</p><div className="mt-1 text-xs"><Markdown source={view.data.mission_context.objective} compact/></div></div><div><p className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">Desired outcome</p><div className="mt-1 text-xs"><Markdown source={view.data.mission_context.desired_outcome ?? "Not specified."} compact/></div></div></div></details>}
        {otherActions.length > 0 && <details className="agent-team-panel rounded-xl"><summary className="flex min-h-11 cursor-pointer list-none items-center gap-2 px-4 text-sm font-semibold"><Activity className="size-4 text-primary"/>More authorized actions · exact targets<Badge className="ml-auto">{groupActionsByTarget(otherActions).length} targets</Badge></summary><div className="border-t border-border p-3"><ActionTargetGroups actions={otherActions} onAction={onAction} actionsCurrent={canMutate} context={{teamId:view.data.team_ref,teamRunId:resolvedTeamRunId,nodeId:view.data.daemon_summary.node_id}} onCompleted={retry}/></div></details>}
      </aside>
    </div>
  </section>;
  return embedded ? content : <main className="agent-team-surface h-full flex-1 overflow-y-auto p-3 sm:p-5"><div className="mx-auto max-w-[1500px]">{content}</div></main>;
}

function HeaderFact({label,value}:{label:string;value:string}) { return <div className="min-w-0 text-[10px]"><dt className="uppercase tracking-wider text-muted-foreground">{label}</dt><dd className="mt-1 break-words font-medium" title={value}>{value}</dd></div>; }
function CurrentDecision({work,compact=false}:{work?:HostConsoleData["all_works"][number];compact?:boolean}) { return work ? <section className={compact ? "border-l-2 border-primary bg-accent/25 px-3 py-2" : "agent-team-section-decision"}><div className="agent-team-eyebrow">Current decision</div><div className={compact ? "mt-1 flex items-center gap-2" : "mt-3 flex items-center justify-between gap-2"}><p className={compact ? "min-w-0 flex-1 truncate text-sm font-semibold" : "company-editorial-title text-lg"}>{work.title || work.work_id}</p><Badge tone={work.condition === "blocked" ? "bad" : work.phase === "review" ? "warn" : "muted"}>{work.condition !== "normal" ? work.condition : work.phase}</Badge></div>{compact ? <p className="mt-1 truncate text-[10px] text-muted-foreground">{work.work_id} · v{work.work_revision} · {work.gate_summary.passed}/{work.gate_summary.required} gates</p> : <dl className="mt-4 space-y-3"><HeaderFact label="Work" value={`${work.work_id} · v${work.work_revision}`}/><HeaderFact label="Binding" value={work.current_member_run_ref ?? "No exact MemberRun binding"}/><HeaderFact label="Gates" value={`${work.gate_summary.passed}/${work.gate_summary.required} passed`}/></dl>}</section> : <section className={compact ? "border-l-2 border-border px-3 py-2" : "agent-team-section-decision"}><div className="agent-team-eyebrow">Current decision</div><p className="mt-2 text-sm font-medium">Select pressure from Lead Inbox</p>{!compact && <p className="mt-1 text-xs text-muted-foreground">Only the Work or interaction bound to the current decision appears here.</p>}</section>; }
function Pressure({label,value,tone}:{label:string;value:number;tone?:"good"|"warn"|"bad"|"running"}) { return <div className="min-w-0 border-r border-border px-2.5 py-2 last:border-r-0"><dt className="truncate text-[9px] uppercase tracking-wider text-muted-foreground">{label}</dt><dd className={`mt-1 text-xl font-semibold tabular-nums ${tone === "good" ? "text-status-good" : tone === "warn" ? "text-status-warn" : tone === "bad" ? "text-status-bad" : tone === "running" ? "text-status-running" : ""}`}>{value}</dd></div>; }
function SideCard({icon:Icon,title,tone,children}:{icon:typeof Activity;title:string;tone?:"warn";children:ReactNode}) { return <section className={`agent-team-panel rounded-xl p-4 ${tone === "warn" ? "border-status-warn/35 bg-status-warn/[0.035]" : ""}`}><div className="mb-3 flex items-center gap-2"><Icon className={`size-4 ${tone === "warn" ? "text-status-warn" : "text-primary"}`}/><h3 className="text-sm font-semibold">{title}</h3></div><div className="space-y-2">{children}</div></section>; }

function groupActionsByTarget(actions:AllowedAction[]) {
  return Array.from(actions.reduce((groups,action) => {
    const key=`${action.target_ref.kind}:${action.target_ref.id}`;
    const current=groups.get(key) ?? [];
    current.push(action);
    groups.set(key,current);
    return groups;
  },new Map<string,AllowedAction[]>()).entries());
}

function ActionTargetGroups({actions,onAction,actionsCurrent,context,onCompleted,className=""}:{actions:AllowedAction[];onAction:RoleActionExecutor;actionsCurrent:boolean;context:{teamId?:string;teamRunId?:string;nodeId?:string};onCompleted:()=>void;className?:string}) {
  return <div className={`divide-y divide-border border-y border-border ${className}`}>{groupActionsByTarget(actions).map(([target,group]) => <section key={target} className="py-3"><p className="mb-2 break-all font-mono text-[10px] font-semibold text-muted-foreground">Target · {target}</p><RoleActionPanel compact actions={group} onAction={onAction} actionsCurrent={actionsCurrent} context={context} onCompleted={onCompleted}/></section>)}</div>;
}
