import { useEffect, useState } from "react";
import { AlertTriangle, GitMerge, Inbox, RadioTower, RefreshCw, ShieldCheck, Users } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Avatar } from "@/components/workbench/Avatar";
import { Markdown } from "@/components/workbench/Markdown";
import { TeamConversationStream } from "@/components/workbench/team/TeamConversation";
import { TeamMembersCapacity } from "@/components/workbench/team/TeamMembersCapacity";
import { TeamMessageComposer } from "@/components/workbench/team/TeamMessageComposer";
import { fetchRoleView, type HostConsoleData, type MessageSummary, type RoleActionExecutor, type RoleView } from "../model/roleViews";
import { AttentionStrip, ViewProvenance, ViewState } from "./RoleViewPrimitives";
import { RoleActionPanel } from "./RoleActionPanel";

export function HostConsole({apiUrl,space,project,teamId,teamRunId,selectedWorkId,selectedMemberRunId,refreshKey,onAction,actionsCurrent,onSelectionChange,embedded=false}:{apiUrl:string;space:string;project:string;teamId:string;teamRunId?:string;selectedWorkId?:string;selectedMemberRunId?:string;refreshKey?:string;onAction:RoleActionExecutor;actionsCurrent:boolean;onSelectionChange:(next:Record<string,unknown>)=>void;embedded?:boolean}) {
  const [view,setView] = useState<RoleView<HostConsoleData>|null>(null);
  const [error,setError] = useState<string|null>(null);
  const [loading,setLoading] = useState(true);
  const [refresh,setRefresh] = useState(0);
  const [replyTo,setReplyTo] = useState<MessageSummary|null>(null);
  useEffect(() => { let live=true; setLoading(true); fetchRoleView<HostConsoleData>(apiUrl,`/v1/views/host-console/${encodeURIComponent(teamId)}`,{space,project}).then((value) => { if(live){setView(value);setError(null);} }).catch((reason) => {if(live)setError(String(reason));}).finally(() => {if(live)setLoading(false);}); return () => {live=false;}; },[apiUrl,space,project,teamId,refreshKey,refresh]);
  const retry = () => setRefresh((value) => value+1);
  if (!view) return <div className="min-h-64"><ViewState loading={loading} error={error} identityLabel={`Host tools · ${teamId}`} onRetry={retry}>{null}</ViewState></div>;

  const allWorks = view.data.all_works;
  const resolvedTeamRunId = teamRunId ?? view.data.team_supervisor?.team_run_id;
  const runScopeMismatch = Boolean(resolvedTeamRunId && view.allowed_actions.some((action) => action.target_ref.kind === "team_run" && action.target_ref.id !== resolvedTeamRunId));
  const selectedWork = allWorks.find((work) => work.work_id === selectedWorkId);
  const selectedMember = view.data.member_runtime.find((member) => member.current_member_run_ref === selectedMemberRunId);
  const contextualActions = view.allowed_actions.filter((action) => (selectedWork && action.target_ref.kind === "work" && action.target_ref.id === selectedWork.work_id) || (selectedMemberRunId && action.target_ref.kind === "member_run" && action.target_ref.id === selectedMemberRunId));
  const contextualKeys = new Set(contextualActions.map((action) => `${action.kind}:${action.target_ref.kind}:${action.target_ref.id}`));
  const fallbackActions = view.allowed_actions.filter((action) => !contextualKeys.has(`${action.kind}:${action.target_ref.kind}:${action.target_ref.id}`) && !["send_message","reply_message","request_decision"].includes(action.kind));
  const canMutate = actionsCurrent && view.freshness === "current" && !loading && !error && !runScopeMismatch;

  const content = <section id="host-tools" className="space-y-4 rounded-xl border border-primary/20 bg-primary/[0.02] p-3 sm:p-4" data-testid="authenticated-host-console" aria-labelledby="host-tools-title">
    <header className="rounded-xl border border-border bg-card px-4 py-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.15em] text-primary"><ShieldCheck className="size-3.5"/>Host-only controls</div><h2 id="host-tools-title" className="mt-1 text-lg font-semibold">Host Console · Lead Inbox, runtime and decisions</h2><p className="mt-1 text-xs text-muted-foreground">Server-authorized tools for {view.data.mission_context?.title ?? view.data.mission_ref}</p></div><div className="flex flex-wrap items-center justify-end gap-2">{embedded && <Button size="sm" variant="secondary" onClick={() => onSelectionChange({teamMode:"workspace"})}>Hide Host tools</Button>}<ViewProvenance view={view}/></div></div>
      <dl className="mt-3 grid gap-2 border-t border-border pt-3 sm:grid-cols-4"><HeaderFact label="Supervisor" value={view.data.team_supervisor ? `${view.data.team_supervisor.status} · generation ${view.data.team_supervisor.generation}` : "Not observed"}/><HeaderFact label="Supervisor authority" value={view.data.team_supervisor ? (view.data.team_supervisor.current ? "Current" : "Expired") : "Unknown"}/><HeaderFact label="NodeDaemon parent" value={`${view.data.daemon_summary.node_id} · ${view.data.daemon_summary.lease_status ?? "unknown"}`}/><HeaderFact label="Recovery" value={view.data.runtime_recovery.length ? `${view.data.runtime_recovery.length} need attention` : "None"}/></dl>
    </header>
    {error && <div role="alert" className="flex flex-wrap items-center gap-2 rounded-lg border border-status-warn/35 bg-status-warn/10 p-3 text-xs"><span className="min-w-0 flex-1">Host tools refresh failed. Last-good truth remains visible; every action is disabled. {error}</span><Button size="sm" variant="secondary" onClick={retry}>Retry</Button></div>}
    {runScopeMismatch && <div role="alert" className="rounded-lg border border-destructive/35 bg-destructive/5 p-3 text-xs">Host actions do not match the selected TeamRun. Controls are disabled until this exact run is projected.</div>}
    {loading && <div role="status" className="flex items-center gap-2 text-xs text-muted-foreground"><RefreshCw className="size-3.5 animate-spin"/>Refreshing Host-only authority…</div>}
    <AttentionStrip view={view}/>
    {view.data.mission_context && <details className="rounded-xl border border-border bg-card"><summary className="min-h-12 cursor-pointer px-4 py-3 text-sm font-semibold">Mission context · {view.data.mission_context.status}</summary><div className="grid gap-3 border-t border-border p-4 lg:grid-cols-2"><div><h3 className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Objective</h3><div className="mt-1 text-xs"><Markdown source={view.data.mission_context.objective} compact/></div></div><div><h3 className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Desired outcome</h3><div className="mt-1 text-xs"><Markdown source={view.data.mission_context.desired_outcome ?? "Not specified."} compact/></div></div></div></details>}
    <div className="grid min-w-0 gap-4 xl:grid-cols-[minmax(0,1fr)_21rem]">
      <div className="min-w-0 space-y-4"><details className="rounded-xl border border-border bg-card" open={view.data.host_inbox.length > 0}><summary className="flex min-h-12 cursor-pointer list-none items-center gap-2 px-4 text-sm font-semibold"><Inbox className="size-4 text-primary"/>Lead Inbox<span className="ml-auto rounded-full bg-primary/10 px-2 py-0.5 text-[10px] text-primary">{view.data.host_inbox.length}</span></summary><div className="border-t border-border p-3"><TeamConversationStream activity={[]} messages={view.data.host_inbox} members={view.data.member_runtime} truncated={false} onOpenWork={(teamWorkId) => onSelectionChange({teamMode:"host",teamWorkId,teamTab:"works"})} onReply={setReplyTo}/></div></details><TeamMessageComposer actions={view.allowed_actions} members={view.data.member_capacity} works={allWorks} replyTo={replyTo} teamId={view.data.team_ref} teamRunId={resolvedTeamRunId} actionsCurrent={canMutate} onAction={onAction} onClearReply={() => setReplyTo(null)} onCompleted={retry}/><details className="rounded-xl border border-border bg-card"><summary className="flex min-h-12 cursor-pointer items-center gap-2 px-4 text-sm font-semibold"><Users className="size-4"/>Member capacity</summary><div className="border-t border-border p-3"><TeamMembersCapacity members={view.data.member_runtime} selectedMemberRunId={selectedMemberRunId} onOpenMember={(memberRunId) => onSelectionChange({teamMode:"host",memberRunId,teamTab:"members"})}/></div></details></div>
      <aside className="min-w-0 space-y-4"><section className="rounded-xl border border-border bg-card p-4"><h3 className="text-sm font-semibold">Host attention</h3><div className="mt-3 grid grid-cols-2 gap-2"><Pressure label="Review" value={view.data.work_queues.review?.length ?? 0}/><Pressure label="Blocked" value={view.data.work_queues.blocked?.length ?? 0}/><Pressure label="Delivery recovery" value={view.data.deliveries_requiring_reconcile.length}/><Pressure label="Gate attention" value={view.data.gate_attention.length}/></div>{view.data.provider_capacity_attention.map((item,index) => <p key={index} className="mt-2 flex gap-2 text-[10px] text-muted-foreground"><AlertTriangle className="size-3 shrink-0"/>{item.reason}</p>)}</section>
        <section className="rounded-xl border border-border bg-card p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><Users className="size-4"/>Selected member context</h3>{selectedMember ? <div className="mt-3 space-y-3 text-xs"><div className="flex items-center gap-3"><Avatar name={selectedMember.display_name} identity={`${selectedMember.agent_member_ref.id} ${selectedMember.role}`} size="lg" tone={selectedMember.runtime_state === "running" ? "running" : selectedMember.capacity === "available" ? "good" : "idle"}/><div className="min-w-0"><p className="truncate font-medium">{selectedMember.display_name}</p><p className="truncate text-muted-foreground">{selectedMember.provider ?? "provider unknown"} · {selectedMember.model ?? "model unknown"}</p></div></div><p>{selectedMember.coordination_status ?? "no coordination status"} · runtime {selectedMember.runtime_state ?? "unknown"}</p><p>Native session {selectedMember.native_session_health ?? "unknown"}</p></div> : <p className="mt-3 text-xs text-muted-foreground">Choose a member in the shared Members tab to scope these controls.</p>}</section>
        {contextualActions.length > 0 && <RoleActionPanel actions={contextualActions} onAction={onAction} actionsCurrent={canMutate} context={{teamId:view.data.team_ref,teamRunId:resolvedTeamRunId}} onCompleted={retry}/>}<details className="rounded-xl border border-border bg-card"><summary className="flex min-h-12 cursor-pointer list-none items-center gap-2 px-4 text-sm font-semibold"><GitMerge className="size-4 text-primary"/>More authorized actions<span className="ml-auto text-[10px] text-muted-foreground">{fallbackActions.length}</span></summary><div className="border-t border-border p-3"><RoleActionPanel actions={fallbackActions} onAction={onAction} actionsCurrent={canMutate} context={{teamId:view.data.team_ref,teamRunId:resolvedTeamRunId}} onCompleted={retry}/></div></details><section className="rounded-xl border border-border bg-card p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><RadioTower className="size-4"/>Runtime fabric</h3><p className="mt-2 text-xs text-muted-foreground">Supervisor and NodeDaemon health are independent. Recovery rows require explicit evidence.</p><p className="mt-3 break-all text-[10px]">{view.data.team_supervisor?.owner_locator ?? "No current Supervisor owner"}</p></section></aside>
    </div>
  </section>;
  return embedded ? content : <main className="h-full flex-1 overflow-y-auto p-3 sm:p-5"><div className="mx-auto max-w-[1500px]">{content}</div></main>;
}

function HeaderFact({label,value}:{label:string;value:string}) { return <div className="min-w-0 text-[10px]"><dt className="uppercase tracking-wider text-muted-foreground">{label}</dt><dd className="mt-1 truncate font-medium" title={value}>{value}</dd></div>; }
function Pressure({label,value}:{label:string;value:number}) { return <div className="rounded-md bg-muted/30 p-2"><dt className="text-[9px] uppercase tracking-wider text-muted-foreground">{label}</dt><dd className="mt-1 text-lg font-semibold tabular-nums">{value}</dd></div>; }
