import { AlertTriangle, ArrowRight, CircleDot, ShieldAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import type { RoleView, WorkSummary } from "../model/roleViews";

export function ViewState({loading,error,children}:{loading:boolean;error:string|null;children:React.ReactNode}){
  if(loading)return <div className="grid min-h-64 place-items-center text-sm text-muted-foreground" role="status">Loading canonical view…</div>;
  if(error)return <div className="m-6 rounded-xl border border-destructive/30 bg-destructive/10 p-5 text-sm text-destructive" role="alert"><ShieldAlert className="mb-2 size-5"/>{error}</div>;
  return <>{children}</>;
}
export function ViewProvenance({view}:{view:RoleView<unknown>}){return <div className="flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground"><Badge>{view.freshness}</Badge><span>{view.schema_version}</span><span>seq {view.as_of_event_sequence}</span><span className="max-w-72 truncate" title={view.source_store_identity}>{view.source_execution_space_id}</span></div>}
export function AttentionStrip({view}:{view:RoleView<unknown>}){if(!view.attention.length&&view.freshness==="current")return null;return <div className="space-y-2">{view.freshness!=="current"&&<div className="flex gap-2 rounded-lg border border-status-warn/40 bg-status-warn/10 p-3 text-xs"><AlertTriangle className="size-4"/>Projection is {view.freshness}; mutations are disabled until current.</div>}{view.attention.map((item)=><div key={`${item.kind}:${item.source_ref.id}`} className="rounded-lg border border-border bg-card p-3 text-xs"><b>{item.reason_code}</b> · {item.recommended_action}</div>)}</div>}
export function WorkTable({items,onOpen}:{items:WorkSummary[];onOpen?:(work:WorkSummary)=>void}){if(!items.length)return <div className="rounded-xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No Work matches this view.</div>;return <div className="overflow-hidden rounded-xl border border-border"><table className="w-full text-left text-xs"><thead className="bg-muted/50 text-muted-foreground"><tr><th className="p-3">Work</th><th>State</th><th>Owner/runtime</th><th>Gates</th><th>Delivery</th><th/></tr></thead><tbody>{items.map((work)=><tr key={work.work_id} className="border-t border-border"><td className="p-3"><div className="font-medium text-foreground">{work.work_id}</div><div className="text-muted-foreground">{work.team_id} · rev {work.work_revision}</div></td><td><Badge>{work.phase}</Badge><div className="mt-1 text-muted-foreground">{work.condition}{work.resolution?` · ${work.resolution}`:""}</div></td><td>{work.owner_actor_ref?.id??"Unassigned"}<div className="text-muted-foreground">{String(work.runtime_summary.state??"unknown")}</div></td><td>{work.gate_summary.passed}/{work.gate_summary.required}<div className="text-muted-foreground">{work.gate_summary.pending} pending</div></td><td><span className="inline-flex items-center gap-1"><CircleDot className="size-3"/>{String(work.delivery_summary.recovery_class)}</span></td><td>{onOpen&&<button className="rounded p-2 hover:bg-muted" onClick={()=>onOpen(work)} aria-label={`Open ${work.work_id}`}><ArrowRight className="size-4"/></button>}</td></tr>)}</tbody></table></div>}
