import { useEffect,useState } from "react";
import { MessagesSquare, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { fetchRoleView,type RoleActionExecutor,type RoleView,type TeamWorkspaceData } from "../model/roleViews";
import type { SelectionState } from "../app/selection";
import { AttentionStrip,ViewProvenance,ViewState,WorkTable } from "./RoleViewPrimitives";
import { HostConsole } from "./HostConsole";
export function TeamWorkspace({apiUrl,space,project,teamId,teamRunId,refreshKey,selection,onAction,actionsCurrent,onSelectionChange}:{apiUrl:string;space:string;project:string;teamId:string;teamRunId?:string;refreshKey?:string;selection:SelectionState;onAction:RoleActionExecutor;actionsCurrent:boolean;onSelectionChange:(next:Partial<SelectionState>)=>void}){
 if(selection.teamMode==="host")return <HostConsole apiUrl={apiUrl} space={space} project={project} teamId={teamId} teamRunId={teamRunId} refreshKey={refreshKey} onAction={onAction} actionsCurrent={actionsCurrent} onSelectionChange={onSelectionChange}/>;
 const [view,setView]=useState<RoleView<TeamWorkspaceData>|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{let live=true;setLoading(true);fetchRoleView<TeamWorkspaceData>(apiUrl,`/v1/views/team-workspace/${encodeURIComponent(teamId)}`,{space,project}).then(v=>{if(live){setView(v);setError(null)}}).catch(e=>live&&setError(String(e))).finally(()=>live&&setLoading(false));return()=>{live=false}},[apiUrl,space,project,teamId,refreshKey]);
 return <div className="h-full flex-1 overflow-y-auto p-4 sm:p-6"><div className="mx-auto max-w-[1500px] space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><div className="mb-2 flex items-center gap-2 text-xs uppercase tracking-[.16em] text-primary"><Users className="size-4"/>Team Workspace</div><h1 className="text-2xl font-semibold">{teamId}</h1><p className="text-sm text-muted-foreground">Mission, Work, Members and delivery truth on one placed Node.</p></div><div className="flex items-center gap-2"><Button size="sm" variant="secondary" onClick={()=>onSelectionChange({teamMode:"host"})}>Open Host Console</Button>{view&&<ViewProvenance view={view}/>}</div></header><ViewState loading={loading} error={error}>{view&&<><AttentionStrip view={view}/><WorkTable items={view.data.works}/><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border border-border p-4"><h2 className="mb-3 font-medium">Members</h2><div className="space-y-2">{view.data.members.map((member,index)=><button key={index} className="flex w-full justify-between rounded-lg bg-muted/40 p-3 text-left text-xs" onClick={()=>member.current_member_run_ref&&onSelectionChange({memberRunId:String(member.current_member_run_ref)})}><span>{String((member.agent_member_ref as {id?:string})?.id??"unknown")}</span><span>{String(member.capacity??"unknown")}</span></button>)}</div></section><section className="rounded-xl border border-border p-4"><h2 className="mb-3 flex items-center gap-2 font-medium"><MessagesSquare className="size-4"/>Messages</h2><div className="space-y-2 text-xs text-muted-foreground">{view.data.messages.length?view.data.messages.map((m,index)=><div key={index} className="rounded-lg bg-muted/40 p-3">{String(m.message_id)} · {String(m.response_intent)}</div>):"No canonical messages."}</div></section></div></>}</ViewState></div></div>
}
