import React, { useRef, useState } from "react";
import { createRoot } from "react-dom/client";

import "../src/index.css";
import { DockShell, useAgentDockController } from "../src/components/workbench/agent/dock";
import type { AgentWorkspaceRosterItem, MessageSummary, WorkSummary } from "../src/model/roleViews";

const actor = (id: string, display_name: string) => ({ kind: "agent_member", id, display_name });
const works: WorkSummary[] = [
  {
    work_id: "work-current", work_revision: 3, team_id: "team-fixture", mission_id: "legacy-none", accountable_team_id: "team-fixture", assignee_membership_id: "membership-member", assignee_kind: "member", assignee_ref: { kind: "member", membership_id: "membership-member", membership_state: "active", agent_member_id: "member", display_name: "Review Agent" }, migration_state: "canonical", title: "Review the provider adapter", context_markdown: "Inspect the adapter boundary and explain any authority drift.", completion_criteria_markdown: "- Exact evidence\n- One canonical Result\n- Host review", claim_mode: "host_assign", eligible_member_ids: ["member"], prerequisite_work_ids: [], successor_work_ids: [], readiness: { state: "not_claimable", reason_codes: [], unsatisfied_prerequisite_work_ids: [], failed_or_cancelled_prerequisite_work_ids: [] }, blocker_reason: null, result_summary: "The adapter preserves native-session truth.", artifact_refs: ["artifact://architecture-review"], check_refs: ["check://focused-pass"], latest_event: { id: "event-review", kind: "submitted", actor_ref: actor("member", "Review Agent"), created_at: "2026-08-31T10:20:00Z" }, owner_actor_ref: actor("member", "Review Agent"), current_member_run_ref: "member-run-current", phase: "review", condition: "normal", resolution: null, priority: "normal", module_refs: [], gate_summary: { required: 1, passed: 1, failed: 0, pending: 0, waived: 0, stale: 0 }, latest_report_ref: "report-result", latest_finding_refs: [], latest_failure_ref: null, delivery_summary: { status: "provider_received" }, runtime_summary: { state: "idle", generation: 1, freshness: "current", work_execution_binding_id: "binding-1", agent_session_id: "session-1", agent_session_generation: 1, provider: "claude", native_session_id: "native-1" }, workspace_summary: { binding_id: "workspace-1", cwd: "/fixture", lifecycle: "attached", safety: "safe" }, delegation_summary: {}, updated_at: "2026-08-31T10:20:00Z",
  },
  {
    work_id: "work-open", work_revision: 1, team_id: "team-fixture", mission_id: "legacy-none", accountable_team_id: "team-fixture", assignee_membership_id: "membership-member", assignee_kind: "member", assignee_ref: { kind: "member", membership_id: "membership-member", membership_state: "active", agent_member_id: "member", display_name: "Review Agent" }, migration_state: "canonical", title: "Map the Work and Message planes", context_markdown: "Document the separate planes.", completion_criteria_markdown: "Keep Work and Messages independent.", claim_mode: "host_assign", eligible_member_ids: ["member"], prerequisite_work_ids: [], successor_work_ids: [], readiness: { state: "ready", reason_codes: [], unsatisfied_prerequisite_work_ids: [], failed_or_cancelled_prerequisite_work_ids: [] }, blocker_reason: null, result_summary: null, artifact_refs: [], check_refs: [], latest_event: null, owner_actor_ref: actor("member", "Review Agent"), current_member_run_ref: null, phase: "open", condition: "normal", resolution: null, priority: "normal", module_refs: [], gate_summary: { required: 0, passed: 0, failed: 0, pending: 0, waived: 0, stale: 0 }, latest_report_ref: null, latest_finding_refs: [], latest_failure_ref: null, delivery_summary: {}, runtime_summary: { state: "unavailable", generation: null, freshness: "conflict_or_unavailable", work_execution_binding_id: null, agent_session_id: null, agent_session_generation: null, provider: null, native_session_id: null }, workspace_summary: { binding_id: null, cwd: null, lifecycle: "unavailable", safety: "unknown" }, delegation_summary: {}, updated_at: "2026-08-31T09:00:00Z",
  },
];
works.push(...Array.from({ length: 16 }, (_, index) => ({
  ...works[1]!,
  work_id: `work-backlog-${index + 1}`,
  title: `Backlog responsibility ${index + 1}`,
  updated_at: `2026-08-31T08:${String(index).padStart(2, "0")}:00Z`,
})));
const messages: MessageSummary[] = [
  { message_id: "message-in", work_id: "work-current", sender: actor("host", "Team Host"), recipients: [actor("member", "Review Agent")], body: "Please connect the final review to the Work acceptance contract.", kind: "coordination", correlation_id: "correlation-review", causation_id: null, response_intent: "response_required", reply_eligible: true, created_at: "2026-08-31T10:10:00Z", delivery_state: "delivered", deliveries: [{ id: "delivery-in", recipient_member_run_id: "member-run-current", status: "delivered", version: 1, provider_receipt_id: null, updated_at: "2026-08-31T10:10:05Z", recipient_identity_id: "member", recipient_display_name: "Review Agent" }] },
  { message_id: "message-out", work_id: null, sender: actor("member", "Review Agent"), recipients: [actor("host", "Team Host")], body: "The review is ready for Host judgment.", kind: "result_summary", correlation_id: "correlation-review", causation_id: "message-in", response_intent: "informational", reply_eligible: true, created_at: "2026-08-31T10:21:00Z", delivery_state: "delivered", deliveries: [{ id: "delivery-out", recipient_member_run_id: "member-run-host", status: "delivered", version: 1, provider_receipt_id: null, updated_at: "2026-08-31T10:21:02Z", recipient_identity_id: "host", recipient_display_name: "Team Host" }] },
  { message_id: "message-separate", work_id: "work-current", sender: actor("host", "Team Host"), recipients: [actor("member", "Review Agent")], body: "This shares Work context but belongs to another exact conversation.", kind: "coordination", correlation_id: "correlation-separate", causation_id: null, response_intent: "informational", reply_eligible: false, created_at: "2026-08-31T09:55:00Z", delivery_state: "acknowledged", deliveries: [{ id: "delivery-separate", recipient_member_run_id: "member-run-current", status: "acknowledged", version: 2, provider_receipt_id: "receipt-separate", updated_at: "2026-08-31T09:55:05Z", recipient_identity_id: "member", recipient_display_name: "Review Agent" }] },
  { message_id: "message-uncorrelated", work_id: "work-current", sender: actor("host", "Team Host"), recipients: [actor("member", "Review Agent")], body: "No correlation means this remains an independent Message.", kind: "coordination", correlation_id: "", causation_id: null, response_intent: "informational", reply_eligible: false, created_at: "2026-08-31T09:50:00Z", delivery_state: "acknowledged", deliveries: [{ id: "delivery-uncorrelated", recipient_member_run_id: "member-run-current", status: "acknowledged", version: 2, provider_receipt_id: "receipt-uncorrelated", updated_at: "2026-08-31T09:50:05Z", recipient_identity_id: "member", recipient_display_name: "Review Agent" }] },
];
works.push({
  ...works[1]!, work_id:"work-recently-closed", title:"Recently closed responsibility", owner_actor_ref:actor("closed-member","Closed Member"), assignee_membership_id:"membership-closed", assignee_ref:{kind:"member",membership_id:"membership-closed",membership_state:"active",agent_member_id:"closed-member",display_name:"Closed Member"}, phase:"closed", resolution:"accepted", readiness:{state:"not_claimable",reason_codes:[],unsatisfied_prerequisite_work_ids:[],failed_or_cancelled_prerequisite_work_ids:[]}, updated_at:"2026-08-31T10:30:00Z",
});
const roster: AgentWorkspaceRosterItem[] = [
  { agent_member_ref: actor("member", "Review Agent"), display_name: "Review Agent", role: "reviewer", is_host: false, organization_status: "active", current_member_run_ref: "member-run-current", runtime_state: "running", capacity: "busy" },
  { agent_member_ref: actor("host", "Team Host"), display_name: "Team Host", role: "host", is_host: true, organization_status: "active", current_member_run_ref: "member-run-host", runtime_state: "idle", capacity: "available" },
  { agent_member_ref: actor("closed-member", "Closed Member"), display_name: "Closed Member", role: "reviewer", is_host: false, organization_status: "active", current_member_run_ref: null, runtime_state: "idle", capacity: "available" },
];

function Fixture() {
  const controller = useAgentDockController({ preferenceKey: "agent-dock-fixture", defaultOpen: false });
  const [messagesFailed, setMessagesFailed] = useState(false);
  const [closedOnly,setClosedOnly]=useState(false);
  const openerRef = useRef<HTMLButtonElement>(null);
  const overlay = window.innerWidth < 1200;
  return <main style={{ display: "grid", gridTemplateColumns: overlay || !controller.state.open ? "1fr" : `minmax(0,1fr) ${controller.state.width}px`, height: "100vh" }}>
    <section data-testid="session-canvas" style={{ minWidth: 0, padding: 24 }}><h1>Provider-native Session</h1><p>Session canvas remains mounted while Work and Messages are inspected.</p><button ref={openerRef} type="button" onClick={() => controller.open("work")}>Open Work</button><button type="button" onClick={() => controller.open("messages")}>Open Messages</button><button type="button" onClick={() => { setMessagesFailed(true); controller.open("messages"); }}>Simulate Messages error</button><button type="button" onClick={()=>{setClosedOnly(true);controller.open("work");}}>Simulate no current Work</button></section>
    <DockShell state={controller.state} onStateChange={controller.setState} displayMode={overlay ? "overlay" : "inline"} works={works} messages={messages} roster={roster} selectedAgentId={closedOnly?"closed-member":"member"} currentWorkId={closedOnly?null:"work-current"} messagesStatus={messagesFailed ? { kind: "error", message: "Canonical Message projection is temporarily unavailable." } : undefined} openerRef={openerRef} onSelectWork={(work) => document.body.dataset.selectedWork = work.work_id} onSelectMessage={(message) => document.body.dataset.selectedMessage = message.message_id}/>
  </main>;
}

createRoot(document.getElementById("root")!).render(<Fixture/>);
