import type { DashboardSnapshot } from "../types";

export const demoSnapshot: DashboardSnapshot = {
  generated_at: new Date("2026-05-29T10:00:00.000Z").toISOString(),
  goals: [
    {
      id: "goal-workbench-rebuild",
      title: "Agent Workbench rebuild",
      objective:
        "Rebuild the frontend as a multi-agent collaboration workbench from page-local layout contracts.",
      owner_agent_id: "agent-lead",
      status: "active",
      success_criteria: [
        "Team workspace reads as persistent collaboration space.",
        "AgentMember has inbox/outbox, timeline, runtime, and actions.",
        "Goal and Task prove assignment, evidence, review, decision, and evaluation.",
        "Desktop, tablet, and mobile screenshots pass PM/User review.",
      ],
      priority: "P0",
      vision_id: "vision-self-hosting-workbench",
      goal_design_id: "goal-design-workbench-rebuild",
      created_at: "2026-05-27T09:00:00.000Z",
      updated_at: "2026-05-29T09:45:00.000Z",
    },
    {
      id: "goal-doc-contracts",
      title: "Page-local layout contracts",
      objective: "Move implementation layout contracts into every page spec.",
      owner_agent_id: "agent-lead",
      status: "complete",
      success_criteria: ["Ten core page specs include detailed ASCII layout contracts."],
    },
    {
      id: "goal-live-members",
      title: "Persistent AgentMember runtime",
      objective: "Make durable members observable and messageable from the Workbench.",
      owner_agent_id: "agent-observer",
      status: "proposed",
      success_criteria: ["Idle members can receive next messages without losing identity."],
    },
  ],
  teams: [
    {
      id: "team-self-hosting",
      name: "Self-hosting Workbench Team",
      description: "Standing team for rebuilding and accepting the Agent Workbench.",
      owner_agent_id: "agent-lead",
      status: "active",
      member_ids: ["agent-lead", "agent-designer", "agent-worker", "agent-critic", "agent-pm", "agent-user"],
    },
  ],
  members: [
    {
      id: "agent-lead",
      name: "Lead",
      role: "Lead",
      status: "active",
      runtime_status: "idle",
      runtime_alive: true,
      runtime_pid: 18001,
      runtime_id: "rt-agent-lead",
      control_endpoint: "unix:///tmp/harness/agent-lead.sock",
      runtime_health: {
        process_alive: true,
        socket_exists: true,
        // Protocol/delivery never probed yet — must surface amber "unknown",
        // not green, even though the process is alive.
        protocol_probe: null,
        delivery_probe: "unknown",
        checked_at: "2026-05-30T09:12:44Z",
      },
      current_task_id: "task-shell-rebuild",
      prompt_ref: ".agents/skills/generic-agent-harness/SKILL.md",
      skill_refs: ["generic-agent-harness", "harness-frontend-product-design"],
      inbox_count: 2,
      queued_count: 1,
      team_ids: ["team-self-hosting"],
    },
    {
      id: "agent-designer",
      name: "Designer",
      role: "Designer",
      status: "active",
      runtime_status: "idle",
      runtime_alive: true,
      current_task_id: "task-page-contracts",
      prompt_ref: ".agents/skills/harness-frontend-product-design/SKILL.md",
      skill_refs: ["harness-frontend-product-design"],
      inbox_count: 1,
      queued_count: 0,
      team_ids: ["team-self-hosting"],
    },
    {
      id: "agent-worker",
      name: "Implementer",
      role: "Worker",
      status: "active",
      runtime_status: "running",
      runtime_alive: true,
      runtime_pid: 18422,
      runtime_id: "rt-agent-worker",
      control_endpoint: "unix:///tmp/harness/agent-worker.sock",
      runtime_health: {
        process_alive: true,
        socket_exists: true,
        protocol_probe: "pass: initialize response received",
        delivery_probe: "pass: turn_completed",
        checked_at: "2026-05-30T09:14:02Z",
      },
      current_task_id: "task-shell-rebuild",
      prompt_ref: "docs/dashboard/frontend-architecture.md",
      skill_refs: ["harness-frontend-product-design"],
      inbox_count: 3,
      queued_count: 0,
      provider_child_thread_count: 1,
      team_ids: ["team-self-hosting"],
    },
    {
      id: "agent-critic",
      name: "Critic",
      role: "Critic",
      status: "active",
      runtime_status: "idle",
      runtime_alive: true,
      current_task_id: "task-critic-screenshot",
      skill_refs: ["harness-frontend-product-design"],
      inbox_count: 1,
      queued_count: 0,
      team_ids: ["team-self-hosting"],
    },
    {
      id: "agent-pm",
      name: "PM Acceptance",
      role: "PM",
      status: "active",
      runtime_status: "idle",
      runtime_alive: true,
      current_task_id: "task-pm-acceptance",
      skill_refs: ["harness-frontend-product-design"],
      inbox_count: 0,
      queued_count: 0,
      team_ids: ["team-self-hosting"],
    },
    {
      id: "agent-user",
      name: "User Acceptance",
      role: "User",
      status: "active",
      runtime_status: "idle",
      runtime_alive: true,
      current_task_id: "task-user-acceptance",
      skill_refs: ["harness-frontend-product-design"],
      inbox_count: 0,
      queued_count: 0,
      team_ids: ["team-self-hosting"],
    },
  ],
  tasks: [
    {
      id: "task-architecture-decision",
      goal_id: "goal-workbench-rebuild",
      title: "Record frontend stack and component decisions",
      objective: "Accept React/Vite/custom primitives and reject shadcn/UI-kit reuse.",
      owner_agent_id: "agent-lead",
      assignee_agent_id: "agent-lead",
      reviewer_agent_id: "agent-critic",
      status: "done",
      branch_ref: "task/agent-workbench-shell-implementation",
      owned_paths: ["docs/dashboard/frontend-architecture.md"],
      acceptance_criteria: ["Stack decision names component primitives and dependency policy."],
    },
    {
      id: "task-page-contracts",
      goal_id: "goal-workbench-rebuild",
      title: "Write page-local layout contracts",
      objective: "Put detailed desktop/tablet/mobile ASCII contracts into every page spec.",
      owner_agent_id: "agent-lead",
      assignee_agent_id: "agent-designer",
      reviewer_agent_id: "agent-critic",
      status: "done",
      depends_on_task_ids: ["task-architecture-decision"],
      branch_ref: "task/agent-workbench-shell-implementation",
      owned_paths: ["docs/dashboard/pages/*.md"],
      acceptance_criteria: ["Every page owns its own Layout Contract section."],
    },
    {
      id: "task-shell-rebuild",
      goal_id: "goal-workbench-rebuild",
      title: "Implement Agent Workbench shell",
      objective: "Build Team-first workbench with persistent members, proof documents, graph/Kanban, docs, warnings, and debug boundary.",
      owner_agent_id: "agent-lead",
      assignee_agent_id: "agent-worker",
      reviewer_agent_id: "agent-critic",
      status: "running",
      depends_on_task_ids: ["task-page-contracts"],
      branch_ref: "task/agent-workbench-shell-implementation",
      pr_ref: "https://github.com/cyl19970726/multi-agent-harness/pull/6",
      owned_paths: ["apps/agent-dashboard/src/**"],
      acceptance_criteria: ["Browser screenshots match page-local layout contracts."],
      workspace_ref: ".harness/worktrees/task-shell-rebuild",
      created_at: "2026-05-28T08:20:00.000Z",
      updated_at: "2026-05-29T09:10:00.000Z",
    },
    {
      id: "task-critic-screenshot",
      goal_id: "goal-workbench-rebuild",
      title: "Implementation screenshot critic",
      objective: "Compare desktop/tablet/mobile screenshots against page-local layout contracts.",
      owner_agent_id: "agent-lead",
      assignee_agent_id: "agent-critic",
      reviewer_agent_id: "agent-lead",
      status: "review",
      depends_on_task_ids: ["task-shell-rebuild"],
      acceptance_criteria: ["Reject dashboard/card-dump first impressions."],
    },
    {
      id: "task-pm-acceptance",
      goal_id: "goal-workbench-rebuild",
      title: "PM acceptance pass",
      objective: "Validate end-to-end product logic through browser screenshots and interaction.",
      owner_agent_id: "agent-lead",
      assignee_agent_id: "agent-pm",
      reviewer_agent_id: "agent-lead",
      status: "planned",
      depends_on_task_ids: ["task-critic-screenshot"],
      acceptance_criteria: ["No unresolved P0/P1 product findings."],
    },
    {
      id: "task-user-acceptance",
      goal_id: "goal-workbench-rebuild",
      title: "User acceptance pass",
      objective: "Validate operator usability through browser screenshots and interaction.",
      owner_agent_id: "agent-lead",
      assignee_agent_id: "agent-user",
      reviewer_agent_id: "agent-lead",
      status: "planned",
      depends_on_task_ids: ["task-critic-screenshot"],
      acceptance_criteria: ["Operator can identify next action without raw JSON."],
    },
  ],
  messages: [
    {
      id: "msg-task-architecture",
      task_id: "task-architecture-decision",
      from_agent_id: "agent-lead",
      to_agent_id: "agent-lead",
      kind: "task",
      delivery_status: "acknowledged",
      content: "Record the accepted stack and Workbench component boundary before implementation.",
      evidence_ids: ["ev-architecture"],
      created_at: "2026-05-29T07:30:00.000Z",
    },
    {
      id: "msg-report-architecture",
      task_id: "task-architecture-decision",
      from_agent_id: "agent-lead",
      to_agent_id: "agent-critic",
      kind: "report",
      delivery_status: "delivered",
      content: "Stack decision recorded: React, TypeScript, Vite, custom Workbench primitives, no shadcn.",
      evidence_ids: ["ev-architecture"],
      created_at: "2026-05-29T07:50:00.000Z",
    },
    {
      id: "msg-task-page-contracts",
      task_id: "task-page-contracts",
      from_agent_id: "agent-lead",
      to_agent_id: "agent-designer",
      kind: "task",
      delivery_status: "acknowledged",
      content: "Move current layouts into each page spec with detailed ASCII contracts.",
      evidence_ids: ["ev-page-contracts"],
      created_at: "2026-05-29T08:00:00.000Z",
    },
    {
      id: "msg-task-shell",
      task_id: "task-shell-rebuild",
      from_agent_id: "agent-lead",
      to_agent_id: "agent-worker",
      kind: "task",
      delivery_status: "acknowledged",
      content: "Implement the Workbench from page-local layout contracts. Do not reuse the rejected shell.",
      evidence_ids: ["ev-page-contracts"],
      created_at: "2026-05-29T08:20:00.000Z",
    },
    {
      id: "msg-worker-report",
      task_id: "task-shell-rebuild",
      from_agent_id: "agent-worker",
      to_agent_id: "agent-lead",
      kind: "report",
      delivery_status: "delivered",
      content: "Workbench shell implementation is in progress; core primitives and surfaces are being rebuilt.",
      evidence_ids: ["ev-architecture"],
      created_at: "2026-05-29T09:10:00.000Z",
    },
    {
      id: "msg-critic-page-contract",
      task_id: "task-page-contracts",
      from_agent_id: "agent-critic",
      to_agent_id: "agent-lead",
      kind: "report",
      delivery_status: "delivered",
      content: "Page-local layout contracts are present for ten core pages; hard-layout specs are historical only.",
      evidence_ids: ["ev-page-contracts"],
      created_at: "2026-05-29T09:30:00.000Z",
    },
    {
      id: "msg-task-critic-screenshot",
      task_id: "task-critic-screenshot",
      from_agent_id: "agent-lead",
      to_agent_id: "agent-critic",
      kind: "task",
      delivery_status: "delivered",
      content: "Review screenshot matrix against page-local layout contracts.",
      evidence_ids: ["ev-page-contracts"],
      created_at: "2026-05-29T09:40:00.000Z",
    },
  ],
  events: [
    {
      id: "event-worker-running",
      agent_member_id: "agent-worker",
      task_id: "task-shell-rebuild",
      event_type: "runtime",
      summary: "Implementer runtime is active on Workbench rebuild.",
      created_at: "2026-05-29T09:12:00.000Z",
    },
    {
      id: "event-critic-idle",
      agent_member_id: "agent-critic",
      task_id: "task-critic-screenshot",
      event_type: "status",
      summary: "Critic is waiting for browser screenshot matrix.",
      created_at: "2026-05-29T09:35:00.000Z",
    },
  ],
  evidence: [
    {
      id: "ev-architecture",
      task_id: "task-architecture-decision",
      source_type: "doc",
      source_ref: "docs/dashboard/frontend-architecture.md",
      summary: "React/Vite/custom Workbench primitive decision; no shadcn.",
    },
    {
      id: "ev-page-contracts",
      task_id: "task-page-contracts",
      source_type: "doc",
      source_ref: "docs/dashboard/pages/*.md",
      summary: "Ten page-local layout contracts with desktop/tablet/mobile ASCII diagrams.",
    },
    {
      id: "ev-reset-screenshot",
      task_id: "task-critic-screenshot",
      source_type: "screenshot",
      source_ref: "agent-workbench-reset-placeholder.png",
      summary: "Reset placeholder verified before rebuild; new screenshots pending.",
    },
    {
      id: "ev-goal-evaluation-gap",
      task_id: null,
      source_type: "goal_evaluation",
      source_ref: "pending",
      summary: "Goal evaluation will be recorded after PM/User browser acceptance.",
    },
  ],
  proposals: [
    {
      id: "proposal-shell-rebuild",
      task_id: "task-shell-rebuild",
      agent_member_id: "agent-worker",
      title: "Workbench shell rebuild",
      summary: "Replace reset placeholder with Team-first Agent Workbench surfaces.",
      status: "draft",
      changed_paths: ["apps/agent-dashboard/src/**", "docs/dashboard/frontend-architecture.md"],
      evidence_ids: ["ev-architecture", "ev-page-contracts"],
    },
  ],
  decisions: [
    {
      id: "decision-stack",
      task_id: "task-architecture-decision",
      decision: "accept",
      rationale: "React/Vite/TypeScript is sufficient; failed UX was caused by product architecture and acceptance gaps, not framework.",
      evidence_ids: ["ev-architecture"],
    },
    {
      id: "decision-page-contracts",
      task_id: "task-page-contracts",
      decision: "accept",
      rationale: "Page-local layout contracts are detailed enough to start implementation.",
      evidence_ids: ["ev-page-contracts"],
    },
  ],
  reviews: [
    {
      id: "review-architecture-1",
      task_id: "task-architecture-decision",
      goal_id: "goal-workbench-rebuild",
      reviewer_agent_id: "agent-critic",
      review_kind: "acceptance",
      verdict: "pass",
      summary:
        "Stack decision is backed by the architecture doc; primitives and dependency policy are explicit. Acceptance gate met.",
      blockers: [],
      residual_risk: "Component-primitive drift if shadcn is reintroduced later.",
      missing_validation: ["Browser screenshot acceptance still pending for the implemented shell."],
      evidence_ids: ["ev-architecture"],
      created_at: "2026-05-29T08:05:00.000Z",
    },
    {
      id: "review-shell-1",
      task_id: "task-shell-rebuild",
      goal_id: "goal-workbench-rebuild",
      reviewer_agent_id: "agent-critic",
      review_kind: "design",
      verdict: "needs_changes",
      summary:
        "Shell rebuild is progressing but the Task surface does not yet render structured reviews; verdict is needs_changes until reviews are legible.",
      blockers: ["Reviews are still shown as unstructured report messages."],
      residual_risk: null,
      missing_validation: ["Desktop/tablet/mobile screenshot matrix against page-local contracts."],
      evidence_ids: ["ev-page-contracts"],
      created_at: "2026-05-29T09:20:00.000Z",
    },
  ],
  gaps: [
    {
      id: "gap-reviews-not-surfaced",
      goal_id: "goal-workbench-rebuild",
      task_id: "task-shell-rebuild",
      category: "observability",
      severity: "p1",
      status: "open",
      summary: "Warnings surface does not yet render the Gap ledger grouped by severity and status.",
      evidence_ids: ["ev-page-contracts"],
      next_step: "Render gapsBySeverity in the Warnings surface with status grouping.",
      owner_agent_id: "agent-worker",
      repro_ref: null,
      closing_test_ref: null,
      created_at: "2026-05-29T09:30:00.000Z",
      updated_at: "2026-05-29T09:30:00.000Z",
    },
    {
      id: "gap-snapshot-key-regression",
      goal_id: "goal-workbench-rebuild",
      task_id: "task-shell-rebuild",
      category: "bug",
      severity: "p0",
      status: "open",
      summary: "Dashboard snapshot intermittently drops the gaps key on empty ledgers.",
      evidence_ids: [],
      next_step: "Add a snapshot serialization test that asserts the gaps key is always present.",
      owner_agent_id: "agent-worker",
      repro_ref: "artifacts/snapshot-missing-gaps.log",
      closing_test_ref: null,
      created_at: "2026-05-29T10:05:00.000Z",
      updated_at: "2026-05-29T10:05:00.000Z",
    },
    {
      id: "gap-mobile-nav-spacing",
      goal_id: "goal-workbench-rebuild",
      task_id: null,
      category: "ux",
      severity: "p2",
      status: "fixed",
      summary: "Rail navigation crowded the header on tablet widths; resolved by collapsing to 5 surfaces.",
      evidence_ids: [],
      next_step: null,
      owner_agent_id: "agent-worker",
      repro_ref: null,
      closing_test_ref: null,
      created_at: "2026-05-28T14:00:00.000Z",
      updated_at: "2026-05-29T08:00:00.000Z",
    },
  ],
  goal_designs: [
    {
      id: "goal-design-workbench-rebuild",
      goal_id: "goal-workbench-rebuild",
      scenario_summary:
        "Rebuild the dashboard as a multi-agent collaboration workbench whose Team, Goal, and Task surfaces each prove assignment, evidence, review, decision, and evaluation.",
      non_goals: [
        "No reuse of the rejected card-dump shell.",
        "No backfill of legacy Evidence-carried learning artifacts.",
      ],
      risk_and_permission_boundaries:
        "Read-only dashboard rendering; no autonomous merges and no live runtime mutation from the UI.",
      required_infra: [
        "dashboard snapshot exposes goal_designs/goal_evaluations/goal_cases/visions",
        "page-local layout contracts for ten core pages",
      ],
      agent_team: "team-self-hosting",
      task_graph: [
        "task-architecture-decision",
        "task-page-contracts",
        "task-shell-rebuild",
        "task-critic-screenshot",
      ],
      evidence_plan: [
        "Desktop/tablet/mobile screenshot matrix against page-local contracts.",
        "Critic review with verdict and residual risk.",
      ],
      acceptance_gates: [
        "PM and User browser acceptance pass with no open P0/P1 findings.",
        "Goal close requires a closeout Decision and a GoalEvaluation.",
      ],
      created_at: "2026-05-27T09:30:00.000Z",
    },
  ],
  goal_evaluations: [
    {
      id: "goal-evaluation-workbench-rebuild",
      goal_id: "goal-workbench-rebuild",
      evaluator_agent_id: "agent-critic",
      outcome: "partial",
      what_worked:
        "Page-local layout contracts gave the implementer an unambiguous target; the proof-document framing made assignment and evidence legible.",
      what_failed:
        "Structured reviews and the learning layer were not surfaced in the first shell pass, so the Goal surface showed counts instead of real sections.",
      missing_infra: ["Browser acceptance automation for the screenshot matrix."],
      missing_evidence: ["PM/User acceptance screenshots for the rebuilt shell."],
      team_design_feedback:
        "A standing self-hosting team with a dedicated critic and PM/User acceptance roles held up well.",
      task_graph_feedback:
        "Linear architecture → contracts → shell → critic graph was sufficient; acceptance fan-out at the end was correct.",
      dashboard_feedback:
        "GoalDocument now renders GoalDesign scenario/non-goals/acceptance-gates and GoalEvaluation what-worked/failed as real sections.",
      reusable_patterns: [
        "Additive-optional schema fields keep old JSONL valid.",
        "Dual-read union (objects + legacy evidence) avoids backfill.",
      ],
      anti_patterns: [
        "Rendering learning artifacts as counts-only.",
        "Adding required fields to existing objects.",
      ],
      follow_up_task_ids: ["task-pm-acceptance", "task-user-acceptance"],
      proposed_goal_ids: ["goal-live-members"],
      created_at: "2026-05-29T09:50:00.000Z",
    },
  ],
  goal_cases: [
    {
      case_id: "goal-case-workbench-rebuild",
      source_goal_id: "goal-workbench-rebuild",
      scenario_type: "frontend-rebuild-from-contracts",
      project_adapter: null,
      goal_design_ref: "goal-design-workbench-rebuild",
      evaluation_ref: "goal-evaluation-workbench-rebuild",
      reusable_patterns: [
        "Page-local layout contracts as the implementer's target.",
        "Proof-document surfaces (assignment→evidence→review→decision→evaluation).",
      ],
      anti_patterns: ["Counts-only rendering of structured artifacts."],
      follow_up_refs: ["goal-live-members"],
      tags: ["frontend", "learning-layer", "self-hosting"],
      created_at: "2026-05-29T10:00:00.000Z",
    },
  ],
  visions: [
    {
      id: "vision-self-hosting-workbench",
      summary:
        "A generic multi-agent harness whose own dashboard is the reference workbench: every goal carries a design, evaluation, and reusable case that feed the next round.",
      source_refs: [
        "docs/dashboard/frontend-design.md",
        "docs/goal-learning-loop.md",
      ],
      created_at: "2026-05-27T08:00:00.000Z",
    },
  ],
  provider_sessions: [
    {
      id: "session-worker-1",
      provider: "codex",
      agent_member_id: "agent-worker",
      task_id: "task-shell-rebuild",
      status: "running",
      command: "codex",
      prompt_summary: "Implement Agent Workbench from page-local layout contracts.",
      started_at: "2026-05-29T09:00:00.000Z",
      evidence_ids: ["ev-architecture"],
    },
  ],
  provider_child_threads: [
    {
      id: "child-thread-critic",
      provider: "codex",
      agent_member_id: "agent-worker",
      task_id: "task-shell-rebuild",
      provider_thread_id: "critic-browser-review",
      provider_agent_nickname: "Screenshot Critic",
      provider_agent_role: "Critic",
      status: "planned",
      created_at: "2026-05-29T09:40:00.000Z",
    },
  ],
  autonomous_proposals: [
    {
      id: "auto-next-browser-gate",
      kind: "follow_up",
      source_type: "next_round_plan",
      source_ref: "docs/dashboard/acceptance.md",
      summary: "After shell implementation, run PM and User browser acceptance agents on screenshot matrix.",
      task_id: "task-shell-rebuild",
      goal_id: "goal-workbench-rebuild",
      disposition: "pending",
      linked_evidence_ids: ["ev-page-contracts"],
      follow_up_task_ids: ["task-pm-acceptance", "task-user-acceptance"],
      created_at: "2026-05-29T09:45:00.000Z",
    },
  ],
  goal_learning_status: [
    {
      goal_id: "goal-workbench-rebuild",
      ok: false,
      warnings: ["GoalEvaluation pending until browser PM/User acceptance completes."],
      task_ids: [
        "task-architecture-decision",
        "task-page-contracts",
        "task-shell-rebuild",
        "task-critic-screenshot",
        "task-pm-acceptance",
        "task-user-acceptance",
      ],
      goal_design: [{ source_ref: "docs/dashboard/frontend-design.md" }],
      goal_evaluation: [],
      goal_cases: [],
      goal_design_objects: [
        {
          id: "goal-design-workbench-rebuild",
          goal_id: "goal-workbench-rebuild",
        },
      ],
      goal_evaluation_objects: [
        {
          id: "goal-evaluation-workbench-rebuild",
          goal_id: "goal-workbench-rebuild",
        },
      ],
      goal_case_objects: [
        {
          case_id: "goal-case-workbench-rebuild",
          source_goal_id: "goal-workbench-rebuild",
        },
      ],
      follow_up_tasks: [],
      member_reports: [],
      decisions: [{ id: "decision-stack" }],
      // Closeout gate (§3.7): a GoalEvaluation object exists but no closeout
      // Decision has been recorded yet, so the goal may not close.
      closeout_decisions: [],
      closeout_waivers: [],
      has_closeout_decision: false,
      has_evaluation: true,
      has_closeout_waiver: false,
      may_close: false,
      closeout_blockers: [
        "missing closeout decision (decision_kind=closeout with >=1 evidence_id)",
      ],
    },
  ],
};
